### ISSUE TITLE
Remove fs-symlink dependency (when no admin access)

### ISSUE THREAD

**Issue by clementbrunel** [Evilweed/protractor-beautiful-reporter#1]
Please consider include this merge request proposed in your forked project. In enterprise conditions, admin acces are very unusual.
https://github.com/bcole/protractor-angular-screenshot-reporter/pull/5

![image](https://cloud.githubusercontent.com/assets/3276077/25183558/31a03604-2518-11e7-9054-ba096bb6d243.png)

Regards

**Comment by Evilweed** [comment]
Thank You for the suggestion.

Fixed in v0.4.3

**Comment by clementbrunel** [comment]
Don't forget to publish on npm :)
