### ISSUE TITLE
Empty Report on Jenkins

### ISSUE THREAD

**Issue by tiberiuzuld** [Evilweed/protractor-beautiful-reporter#10]
Hi @Evilweed ,

Locally the html report works correctly.
In Jenkins `app.js` file the `this.results` was empty array.
`combined.json` has the test run data inside.

When loading the file from Jenkins HTML publish that the report loads but does not fetch correctly
`http://<domain-name>/jenkins/view/<view-name>/job/<job-name>/HTML_Report/%7B%7Bresult.screenShotFile%7D%7D`
Request Method:GET
Status Code:404 Not Found

I am using:
* [HTML Publisher Plugin](https://wiki.jenkins.io/display/JENKINS/HTML+Publisher+Plugin)
* Jasmine2
* protractor v5.1.2

```javascript
   jasmine.getEnv().addReporter(new HtmlReporter({
      baseDirectory: 'e2e/screenShots',
      takeScreenShotsForSkippedSpecs: true,
      docName: 'index.html'
    }).getJasmine2Reporter());
```

**Comment by Evilweed** [comment]
I'm not using Jenkins, never tried to integrate my script into it, and sadly don't have time to do it. If someone will figure out where the issue lies then i can merge someone's fix into protractor-beautiful-reporter. @tiberiuzuld - let me know if You managed to make it work.

**Comment by miller45** [comment]
ich have pull request which covers this maybe. It eleminates the %7B%7Bresult.screenShotFile%7D%7D in my case...
https://github.com/Evilweed/protractor-beautiful-reporter/pull/13

**Comment by tiberiuzuld** [comment]
Hi @Evilweed ,
I no longer use this library, moved to [this](https://github.com/Kenzitron/protractor-jasmine2-html-reporter) since then.

I think you need to use  or some other internal protractor api 
```
/**
   * A callback function called once all tests have finished running and
   * the WebDriver instance has been shut down. It is passed the exit code
   * (0 if the tests passed). afterLaunch must return a promise if you want
   * asynchronous code to be executed before the program exits.
   * This is called only once before the program exits (after onCleanUp).
   */
  afterLaunch?: (exitCode: number) => void;
```
To create the report and for tests not to finish till the report is done.
In my case jenkins was collecting the files before the report was written to disk.

Thanks,

**Comment by Evilweed** [comment]
Should no longe occur.

**Comment by jen-v** [comment]
Any instructions on how to integrate this package with Jenkins? I cannot see the `tmp` file in Workspace, seems like the Report is not running on Jenkins?
