### ISSUE TITLE
Html report looks like broken

### ISSUE THREAD

**Issue by shulolo** [Evilweed/protractor-beautiful-reporter#100]
Hi,

I used protractor-beautiful-reporter on my local environment and it looks fine.
But when I use it in a server, I opened my HTML report and I have variables in brackets.
For example, instead to have the test name, I have {{ctrl.currentParent = ctrl.getSpec(result.description)}} disaplyed on my HTML report.
Is this possble? Do you know if there is a solution tot his?

Thank you in advance.

**Comment by miller45** [comment]
@shulolo If you press F12 and look at the "console" do you see an error message ? 
In general the page works on servers but the many things that can happen therefore i need the output of the console...

**Comment by shulolo** [comment]
Hi,

So I checked it and I have this on the console :

Content Security Policy: The page’s settings blocked the loading of a resource at https://fonts.googleapis.com/css?family=Roboto:300,400,500,700
Content Security Policy: The page’s settings blocked the loading of a resource at http://XXX/reportTests/fonts/glyphicons-halflings-regular.woff2 (« default-src 'none' »).
Content Security Policy: The page’s settings blocked the loading of a resource at http://XXX/reportTests/fonts/glyphicons-halflings-regular.woff (« default-src 'none' »).
Content Security Policy: The page’s settings blocked the loading of a resource at http://XXX/reportTests/fonts/glyphicons-halflings-regular.ttf (« default-src 'none' »).

And in the Network tab there is just the request for the HTML page with a 200 status code.

Do you need something else?

Thank you.

**Comment by miller45** [comment]
@shulolo the" Content Security Policy: The page’s settings blocked the loading of a resource at "
look suspicous... Could be your server has to be configured to handle .tff or woff files. (Is it a microsoft server?)
Did you copy all files for the report? Are you using the latest version? (v.1.2.5)
>Also, I noticed that the js files are not loaded on the request sent. I can see css files but no js files.
This looks like you have activated the filter in the network tab....(make sure that you did dont click on "CSS" ...
Please do the following open your "network tab" and open the page. [https://www.elektrofisch.de/pbrexample/report.html](https://www.elektrofisch.de/pbrexample/report.html)

**Comment by shulolo** [comment]
Hi I confirm that this is a CSP issue.
It blocked all the JavaScript.
I changed the configuration and it works now.
About the Network tab, what I talked about was on the console, not in the Network tab, and there was no filter.

Thank you.
