### ISSUE TITLE
The reporter throws exceptions for the .lock file (running multiple reporter instances)

### ISSUE THREAD

**Issue by laflaneuse** [Evilweed/protractor-beautiful-reporter#104]
Hi,

I am using version 1.2.5 of the reporter (beautiful indeed!) and when my tests run I get the following exceptions

build	03-Oct-2018 20:46:26	[chrome #01-17] { Error: EEXIST: file already exists, mkdir 'out/test/reports/e2e/.lock'
build	03-Oct-2018 20:46:26	[chrome #01-17]     at Object.fs.mkdirSync (fs.js:885:18)
build	03-Oct-2018 20:46:26	[chrome #01-17]     at Object.addMetaData (/aw/node_modules/protractor-beautiful-reporter/index.js:5205:12)
build	03-Oct-2018 20:46:26	[chrome #01-17]     at Jasmine2Reporter._callee8$ (/aw/node_modules/protractor-beautiful-reporter/index.js:4986:38)
build	03-Oct-2018 20:46:26	[chrome #01-17]     at tryCatch (/aw/node_modules/protractor-beautiful-reporter/index.js:5403:40)
build	03-Oct-2018 20:46:26	[chrome #01-17]     at Generator.invoke [as _invoke] (/aw/node_modules/protractor-beautiful-reporter/index.js:5677:22)
build	03-Oct-2018 20:46:26	[chrome #01-17]     at Generator.prototype.(anonymous function) [as next] (/aw/node_modules/protractor-beautiful-reporter/index.js:5436:21)
build	03-Oct-2018 20:46:26	[chrome #01-17]     at step (/aw/node_modules/protractor-beautiful-reporter/index.js:4487:191)
build	03-Oct-2018 20:46:26	[chrome #01-17]     at /aw/node_modules/protractor-beautiful-reporter/index.js:4487:361
build	03-Oct-2018 20:46:26	[chrome #01-17]     at <anonymous>
build	03-Oct-2018 20:46:26	[chrome #01-17]     at process._tickCallback (internal/process/next_tick.js:189:7)
build	03-Oct-2018 20:46:26	[chrome #01-17]   errno: -17,
build	03-Oct-2018 20:46:26	[chrome #01-17]   code: 'EEXIST',
build	03-Oct-2018 20:46:26	[chrome #01-17]   syscall: 'mkdir',
build	03-Oct-2018 20:46:26	[chrome #01-17]   path: 'out/test/reports/e2e/.lock' }
build	03-Oct-2018 20:46:26	[chrome #01-17] Could not save JSON for data: [object Object]

My reporter configuration in protractor : 
const HtmlReporter = require('protractor-beautiful-reporter');
...
onPrepare() {
...
      jasmine.getEnv().addReporter(new HtmlReporter({
        baseDirectory: 'out/test/reports/e2e/',
        screenshotsSubfolder: 'screenshots',
        jsonsSubfolder: 'jsons',
        takeScreenShotsOnlyForFailedSpecs: true,
        pathBuilder: function pathBuilder(spec, descriptions, results, capabilities) {
          return join(fileName + '_' + descriptions.join('-').replace(/\"/g,''));
        },
        sortFunction: function sortFunction(a, b) {
          if (a.instanceId == b.instanceId) {
            if( a.timestamp < b.timestamp) {
              return -1;
            } else {
              return 1;
            }
          } else {
            if (a.instanceId < b.instanceId) {
              return -1;
            } else {
              return 1;
            }
          }
        }
        }).getJasmine2Reporter());
...}

It would be great if this could be addressed, as I would love to use this for our project. 

Many thanks!

**Comment by miller45** [comment]
@laflaneuse before i can dig into details...
can ask you for two things first?:
- Delete the lock file manually
- Delete the pathBuilder function 
And then see if it works?

**Comment by laflaneuse** [comment]
Many thanks for the quick reply.
The first suggestion is not a viable one I am afraid - I am running the tests in a bamboo plan and additionally in a docker, which is then removed. Locally I have not managed to reproduce this.
I will try out the second suggestion and come back to you, many thanks!

**Comment by miller45** [comment]
Ok the docker container would not contain an existing file anyway (except you have a volume mapping).

**Comment by laflaneuse** [comment]
I tried it out without the pathBuilder function and it is still failing with the same error message.  
Interestingly we are starting the docker container with a volume mapping
docker run -dti -v $(pwd)/out:/aw/out --net=host --privileged --name test image:latest
but the directory 'out 'which you see referenced also in the exception ('out/test/reports/e2e/.lock') is generated during the execution of the testcases. 
Any ideas?

**Comment by miller45** [comment]
First: The reporter is actually checking if the .lock directory exists before it tries to create one...so the exception shows the this check is failing or we have race condition....
Second: Do you know if the docker process have the correct user permissions to access to mapped volume?
For ruling this out you could first let the tests run without volume mapping (of course you have no access to the results but this is how you can find out what the problem might be)
With volume mapping it could also be that there are other docker processes (still) running at the same time (maybe you forgot that one is still running) that access the directory simultaneously...

**Comment by laflaneuse** [comment]
Also just reproduced locally

chrome #01-17] 
[chrome #01-17]          column
[chrome #01-17]             ✓ should exist
[chrome #01-17] { Error: EEXIST: file already exists, mkdir 'out/test/reports/e2e/.lock'
[chrome #01-17]     at Object.fs.mkdirSync (fs.js:885:18)
[chrome #01-17]     at Object.addMetaData (/home/els/Documents/pro/aw/node_modules/protractor-beautiful-reporter/index.js:5205:12)
[chrome #01-17]     at Jasmine2Reporter._callee8$ (/home/els/Documents/pro/aw/node_modules/protractor-beautiful-reporter/index.js:4986:38)
[chrome #01-17]     at tryCatch (/home/els/Documents/pro/aw/node_modules/protractor-beautiful-reporter/index.js:5403:40)
[chrome #01-17]     at Generator.invoke [as _invoke] (/home/els/Documents/pro/aw/node_modules/protractor-beautiful-reporter/index.js:5677:22)
[chrome #01-17]     at Generator.prototype.(anonymous function) [as next] (/home/els/Documents/pro/aw/node_modules/protractor-beautiful-reporter/index.js:5436:21)
[chrome #01-17]     at step (/home/els/Documents/pro/aw/node_modules/protractor-beautiful-reporter/index.js:4487:191)
[chrome #01-17]     at /home/els/Documents/pro/aw/node_modules/protractor-beautiful-reporter/index.js:4487:361
[chrome #01-17]     at <anonymous>
[chrome #01-17]     at process._tickCallback (internal/process/next_tick.js:188:7)
[chrome #01-17]   errno: -17,
[chrome #01-17]   code: 'EEXIST',
[chrome #01-17]   syscall: 'mkdir',
[chrome #01-17]   path: 'out/test/reports/e2e/.lock' }
[chrome #01-17] Could not save JSON for data: [object Object]
[chrome #01-17]             ✓ should not indicate the  column is sorted initially

**Comment by miller45** [comment]
I see...well testing sharding is also a kind of parrallelsation as this item suggests https://github.com/angular/protractor/issues/569. But do not have personal experience with sharding.
As i see in the examples from this repo...you have to have different report for every shard...so if you splitting up the directories with the pathBuilder....

**Comment by miller45** [comment]
ahh what is that join function in your protractor.conf?
```return join(fileName + '_' + descriptions.join('-').replace(/"/g,''));
````
? i cannot see were you import that function?

**Comment by laflaneuse** [comment]
In the latest example I sent you I am no longer using the pathBuilder. I actually used a different path because we are also using protractor-retry 
https://www.npmjs.com/package/protractor-retry
and my scope is to get a general report at the end of all runs with all testcases. If a testcase was not successful but then got fixed the next time, it should be shown only once and as green at the final report ;) So, that is the dream that I am trying to accomplish with the beautiful reporter 😄 
Also, the join function is nothing more than : 
const { join } = require('path');
(not very clear naming, I have to admit)

**Comment by miller45** [comment]
Ahh ok i see your vision is nice and absolutely valid...
but i am really sorry...the reporter "as it is" can only run in parallel when writing to different directories. It is bound to fail when running parallel in the same directory...i am really sorry...
the only solution i see is having the parallel instance running in different target directories and then merge the results afterwards in one directory...
maybe @Evilweed has a different perspective to offer?
