### ISSUE TITLE
Last test is not displayed in report

### ISSUE THREAD

**Issue by atrascau** [Evilweed/protractor-beautiful-reporter#11]
I have a test with 7 it conditions. In the generated report only the first 6 are displayed.

**Comment by Evilweed** [comment]
Are You using latest version?
Are You using Jasmine 2.0?
Can You provide smallest test case i can run to reproduce this issue?

**Comment by Evilweed** [comment]
Should be fixed for Jasmine2. I will be dropping support for Jasmine 1 soon. Can You check if it fixes your issue?
