### ISSUE TITLE
Report.html blank page zero bytes

### ISSUE THREAD

**Issue by Edgar56** [Evilweed/protractor-beautiful-reporter#110]
My conf.js file:

const HtmlReporter = require('protractor-beautiful-reporter');

exports.config = {
  onPrepare: () => {
    //Add a screenshot reporter and store sreenshots to `/tmp/screenshots`:
    jasmine.getEnv().addReporter(new HtmlReporter({
      baseDirectory: 'Reports/screenshots',
      screenshotsSubfolder: 'images'
   }).getJasmine2Reporter());
    
   
      

    browser.manage().timeouts().implicitlyWait(9000);
  },
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['reportToolTest.js'],
};
package.json file:
{
  "name": "protractortask11",
  "version": "1.0.0",
  "description": "",
  "main": "FirstTask.js",
  "dependencies": {
    "jasmine": "^3.2.0",
    "protractor-beautiful-reporter": "^1.2.5"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "u
  },
  "author": "",
  "license": "ISC",
}

I did what everything what write in documentation, ss appears with image, but html reports just white screen.

**Comment by miller45** [comment]
I do not see browser stuff in your config file like  
` capabilities: {
        browserName: 'chrome',
} 
`
did you leave it out?

Do you have and error message on the console?
Is the screen really completly white without any text?

Though it will not alter your outcome, you should add jasmine and protractor-beautiful-reporter to devDependencies not dependencies.

**Comment by Edgar56** [comment]
reportToolTest.js file : 
describe('Open all pages', () => {


    beforeEach(function () {
        
        browser.get('https://www.angularjs.org');
    });

    it('should fail as greeting text is different', function () {
        page.yourNameInputField.sendKeys('Julie');
        expect(page.greetingText.getText()).toEqual('Hello Julie hello!');
    });

});

**Comment by Edgar56** [comment]
I fix problem with html file now is not empty, just added 3 test case, but app.js still empty.

**Comment by miller45** [comment]
I see you have the configuration from our example. How do you start the tests now...with grunt test:e2e ?

**Comment by Edgar56** [comment]
Chrome, I can send mine code to you to check it, if needs

**Comment by miller45** [comment]
@Edgar56 I strongly to start with an e2e test tutorial like this: https://www.protractortest.org/#/tutorial

And you didn´t answer my question from before where I asked how you start the e2e tests, because that is very important as you see in a moment.

Here is the solution to run the your "tests".
You should add a line with `"e2e": "protractor conf.js"` to scripts section in the `package.json` so it looks like this:
```
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start":"reportToolTest.js",
    "e2e": "protractor conf.js"
  },
```
Because then you can start the tests with command `npm run e2e`
I did this with your example and it works.
BTW: you have to start e2e tests with "protractor" and not by directly calling the javascript file with tests (like your `start` entry is suggesting).
Maybe you should also a line to make sure the webdrivers are installed always so the scripts sections looks like this.
```
 "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "reportToolTest.js",
    "prepare": "webdriver-manager update",
    "e2e": "protractor conf.js"
  },
```
So when you do `npm install` you can always start the tests with `npm run e2e` without bothering everything else...

**Comment by Edgar56** [comment]
Iam starting like that: protractor conf.js

**Comment by miller45** [comment]
>Can you explain why it works when using "npm run e2e", but not with "protractor conf.js" ? IT WORKS
@Edgar56 ahh very good
(Possible) Explanation: 
When you start protractor directly from the command line you start it from your global installation but not the "version" you have in your development folder (where you have your package.json).
By putting the launch command in your package.json and starting it via npm, you ensure that you use the version which is installed in your local `node_modules` folder.

This does not explain why it didn´t work with your global version, but  it is anyway a good practice to use only the version from your package.json. E.g. if you have multiple projects using different versions of protractor you would not be able to tell problem.

**more background**
enter `which protractor` (windows) or `where protactor` (linux) on the command line and observe the output. It will print out the location of your global installation of protractor (or nothing if you don ´t have installed globally at all).

By putting the `protractor` in your script section your command is transformed to the equivalent of :
`node node_modules/protractor/bin/protractor conf.js`
The same with `webdriver-manager update`, it is transformed like this:
`node node_modules/protractor/bin/webdriver-manager update`

**Comment by Edgar56** [comment]
When i run with: npm run e2e, i getting: 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! protractorreporttool@1.0.0 e2e: `protractor conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protractorreporttool@1.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Edgar\AppData\Roaming\npm-cache\_logs\2018-10-26T11_45_04_727Z-debug.log. Maybe you know what happing? I google a lot, tried delete node_modules, need all packages npm ir etc, and nothing.
[2018-10-26T11_45_04_727Z-debug.log](https://github.com/Evilweed/protractor-beautiful-reporter/files/2519035/2018-10-26T11_45_04_727Z-debug.log)

**Comment by Edgar56** [comment]
Okey, thanks again

**Comment by Edgar56** [comment]
Hey Miller, 
is there any way to create it folder for differents spec?

**Comment by miller45** [comment]
There are ways do want to split a specific level? Or by browser? You can have a look at the pathbuilder in our front README page.
