### ISSUE TITLE
Timestamp in report/index.html

### ISSUE THREAD

**Issue by kerkeniakov** [Evilweed/protractor-beautiful-reporter#119]
Can we have timestamp of testcase run ? like this :
![image](https://user-images.githubusercontent.com/28395932/48412769-5f788780-e74e-11e8-8d98-6f143300b625.png)

**Comment by miller45** [comment]
@kerkeniakov you mean in the title?

**Comment by miller45** [comment]
In that case just add the timestamp to the "title" like this:

```
jasmine.getEnv().addReporter(new HtmlReporter({    
            baseDirectory: 'reports-tmp',
            docTitle: "E2E tests from " + new Date().toLocaleString(),
        }).getJasmine2Reporter());
```

**Comment by kerkeniakov** [comment]
Thanks , this works great.
However I suggest that you parse timestamps from the json results.
For example each console error could have a timestamp prefix and each `it` block/step.
This greatly helps when you are looking at error logs serverside and comparing from report.
