### ISSUE TITLE
Document "useAjax" option in ClientDefaults

### ISSUE THREAD

**Issue by BrunoBieri** [Evilweed/protractor-beautiful-reporter#123]
This is an enhancement.
Please document how to use the "useAjax" feature in the ClientDefaults settings in the Readme file.
Thank you.

**Comment by miller45** [comment]
@BrunoBieri Ok done now...
https://github.com/Evilweed/protractor-beautiful-reporter/blob/master/README.md#load-spec-results-via-ajax
