### ISSUE TITLE
Missing sentence end in Readme.md 

### ISSUE THREAD

**Issue by BrunoBieri** [Evilweed/protractor-beautiful-reporter#124]
In the current Readme.md the sentance under the title "Important" (on the top) ends like:

> Version 1.2.6: needs an extra parameter 'clientDefaults: {}' in the options block else you will get an

I would expect the sentance to tell me what will happen if the "clientDefaults" options block actually is missing.

**Comment by miller45** [comment]
Thank for pointing this out...the sentence was obsolete anyway now it says:
 If you get `Error: TypeError: Cannot set property 'searchSettings' of undefined` use at least version 1.2.7, where the bug has been fixed

**Comment by BrunoBieri** [comment]
Very good thank you.
