### ISSUE TITLE
How to add current browser name to baseDirectory & docName on the fly with multi-capability setting in conf.js

### ISSUE THREAD

**Issue by vickyru** [Evilweed/protractor-beautiful-reporter#128]
First of all thank you for providing such a nice package for test reporting.

If user wants to generate multiple report for multiple browser with inline browser name (baseDirectory & docName) then how to achieve it.

base directory ==> reports-browser-name
doc name ==> results-browser-name-CurrentTime

I tried many option like browser.capabilities & getProcessConfig etc in conf.js file but no luck yet as these method do not return browser name out of their method scope.

Tech Stack:
    "protractor": "^5.4.1",
    "protractor-beautiful-reporter": "1.2.7",

**Comment by miller45** [comment]
I though this example would should how to do this but having a closer look I see the that the line with browsername is commented out:
https://github.com/Evilweed/protractor-beautiful-reporter/blob/master/examples/protractor.jasmine2.with.sharding.sort2.conf.js

@Evilweed do you have a clou if this would work (browsername in baseDirectory)?

**Comment by miller45** [comment]
First let me point out (for other readers) that protractor-beautiful-reporter supports e2e test in one single report page (see browser column)...

**Comment by miller45** [comment]
Here is an working example where you have the results for each browser in seperate directories (of course some variables have to adjusted to your environment:
Important: you have to store the time into a variable outside the pathbuilder as you can see in the following example
```
const HtmlReporter = require('protractor-beautiful-reporter');
const path = require('path');

function makeuuid() {
    function s4() {
        return Math.floor((1 + Math.random()) * 0x10000)
            .toString(16)
            .substring(1);
    }
    return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
        s4() + '-' + s4() + s4() + s4();
}

exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: [
        './e2e/*_spec.js'
    ],
    multiCapabilities: [
        {browserName: 'chrome'},
        {browserName: 'firefox'}
    ],
    framework: 'jasmine',
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 30000,
        print: function () {
        }
    },
    onPrepare() {
        const reportDate = new Date();
        const reportTime = `${reportDate.getHours()}-${reportDate.getMinutes()}-${reportDate.getSeconds()}`;
        jasmine.getEnv().addReporter(
            new HtmlReporter({
                baseDirectory: 'e2e-report',
                screenshotsSubfolder: 'screenshots',
                docTitle: `e2e from ${reportTime}`,
                pathBuilder: function pathBuilder(spec, descriptions, results, capabilities) {
                    let browserName = capabilities.get('browserName');
                    return path.join(
                        browserName,
                        makeuuid());
                }
            }).getJasmine2Reporter()
        );

    }

};
```

**Comment by vickyru** [comment]
Thanks @miller45 for quick and 💯 % accurate response. Problem resolved. Closing issue 👍
