### ISSUE TITLE
if useAjax enabled report is not displayed

### ISSUE THREAD

**Issue by BrunoBieri** [Evilweed/protractor-beautiful-reporter#131]
I'm using the following settings:

> screenshotsSubfolder: 'image',
jsonsSubfolder: 'json',
clientDefaults:{
  useAjax:true,
  searchSettings:{
    allselected: true,
    passed: true,
    failed: true,
    pending: true,
    withLog: true
  }
}

All the test files are generated but if I open the report it's empty. The developer console of my browser reports:

> Access to XMLHttpRequest at 'http://pathToReport/html/combined.json' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Manual workaround is to download all files and do two changes on the "combined.json" file:
- Remove leading and ending quote character "
- Replace escaping for quote character \" with a normal quote character "

**Comment by BrunoBieri** [comment]
Seems like it's the Jenkins content security setting hudson.model.DirectoryBrowserSupport.CSP.

It was set to:
hudson.model.DirectoryBrowserSupport.CSP='sandbox allow-scripts' 

and needed to be changed to:
hudson.model.DirectoryBrowserSupport.CSP='' 

See Jenkins content security description:
https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy

**Comment by miller45** [comment]
Of course to use ajax it has to allowed by CSPs. maybe adding "connect-src" should have worked too.
