### ISSUE TITLE
New line support in spec description

### ISSUE THREAD

**Issue by yuriy-khortashko** [Evilweed/protractor-beautiful-reporter#132]
My tests are organized in such way, that one spec (or test scenario) covers few acceptance use cases.
Would be great to have a possibility to add a new line to scenario description. This would make them readable in test report

Please see screenshot:
![beautiful_reporter_new_line_in_spec_name](https://user-images.githubusercontent.com/16326238/51637859-88df3c00-1f65-11e9-8930-3fc4acd11d07.png)

Can a new line support be added to spec description?

(I have started to use protractor-beautiful-reporter and am really excited.
It gives a very good visibility of my work.
Thank you, the team is doing a great job!)

**Comment by miller45** [comment]
@yuriy-khortashko I found out how to support newlines in spec or testcase descriptions (No HTML markdown possible though). It is describe in the wiki under [linebreaks in specs or testcase](https://github.com/Evilweed/protractor-beautiful-reporter/wiki/linebreaks-in-specs-or-testcase)

**Comment by yuriy-khortashko** [comment]
Thanks!
