### ISSUE TITLE
Release of 1.2.8 version: Don't fail test if test fails to take screenshot

### ISSUE THREAD

**Issue by amangoel49** [Evilweed/protractor-beautiful-reporter#146]
We are waiting for [fix](https://github.com/Evilweed/protractor-beautiful-reporter/pull/143) when will it be released ?

**Comment by amangoel49** [comment]
cc @miller45

**Comment by miller45** [comment]
I think the release will be done 1-2 Days...

**Comment by miller45** [comment]
@Evilweed Can you can release the 1.2.8 version?

**Comment by miller45** [comment]
@amangoel49 I might be the @Evilweed has holidays or is too busy right now...so the release is still pending....

**Comment by miller45** [comment]
@amangoel49 I released the fix now with version 1.2.8 (merge #143)

**Comment by amangoel49** [comment]
Thanks :)
