### ISSUE TITLE
Report fails to generate

### ISSUE THREAD

**Issue by esmiralha** [Evilweed/protractor-beautiful-reporter#148]
After running a spec with a single it, the following error appears in the console:

An error was thrown in an afterAll
AfterAll Failed: timeout: Timed out receiving message from renderer: 10.000
  (Session info: chrome=74.0.3729.157)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Mac OS X 10.14.5 x86_64)

And no report is generated.

**Comment by miller45** [comment]
and when you remove the reporter the test work? The reporter is working with chrome 74.0.3729.169 on my system 
```
    (Session info: chrome=74.0.3729.169)
      (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64)
```

**Comment by esmiralha** [comment]
The error is unrelated to the reporter. It happens when browser.takeScreenshot is invoked. I have found a possibly related issue in Protractor that matches my current environment (Cordova hybrid app). I am closing this issue... Thanks for your help!
