### ISSUE TITLE
FEATURE: Add a config setting to change height of image dialog.

### ISSUE THREAD

**Issue by RonanDConnolly** [Evilweed/protractor-beautiful-reporter#150]

**Comment by miller45** [comment]
@RonanC Try out this option in the reporter
customCssInline: `.modal-lg { width: 88% }` 
This overrides the fixed width from bootstrap.css, the height will adjust accordingly.
Does this work for you?

**Comment by RonanC** [comment]
That worked!
I found that 100% was too much, but 90% looked great.
```ts
customCssInline: `.modal-lg { width: 90% }`
```

**Comment by RonanC** [comment]
I do think that perhaps 90% would be a good default as you want screenshots of an entire web app to be as big as possible.
