### ISSUE TITLE
FEATURE: Enable left/right keys to switch between images in the image dialog.

### ISSUE THREAD

**Issue by RonanDConnolly** [Evilweed/protractor-beautiful-reporter#151]
# Why
This will allow quick navigation between screenshots.
It's a frustration experience to have to use the mouse when intuitively you would go for the arrow keys (gets me every time!).

**Comment by miller45** [comment]
@RonanDConnolly Version 1.3.0 just released with your feature (thanks for the contribution)

**Comment by RonanDConnolly** [comment]
Awesome, thanks 😁🛠️
