### ISSUE TITLE
How to disable the screenshot feature

### ISSUE THREAD

**Issue by ManikDhar** [Evilweed/protractor-beautiful-reporter#153]
I want to disable the screen-shot feature (don't want any screen-shot in my generated report), But not getting any option to disable.

There is an option to take screenshot only for failed tests.

Please suggest.

**Comment by miller45** [comment]
Currently there is no option for disabling screenshots

**Comment by miller45** [comment]
@ManikDhar I just released the version 1.2.10 with the `disableScreenshots` option
