### ISSUE TITLE
Group test by browser

### ISSUE THREAD

**Issue by gandadil** [Evilweed/protractor-beautiful-reporter#155]
I have run my e2e test of chrome and firefox simultaneous with multiCapabilities enabled in protractor.conf.js. The problem is the report results that have a mix of browser per section/describe. I need a option to filter the report to view just one browser at time or group the sections by browser.
I tried use maxSessions: 1 on protractor.conf.js to execute the tests sequentially (chrome first, firefox second), but the report have just firefox results, maybe because property preserveDirectory is false. I can't set this property to true because i need the results overwrited every run.
Other way to resolve my problem is to generate different pages for each browser and report.html will have a link to each report.

**Comment by dharnapahuja** [comment]
This would definitely be very useful.

**Comment by miller45** [comment]
@gandadi and @dharnapahuja 
 preservedirectory must be true,. but you can just delete the dir in beforeLaunce of protractor.js.
e.g.
```   beforeLaunch: function(){
        rimraf.sync("./reports-tmp");
    },
```
But you also have to set shardTestfiles... I had all tests sorted by browsers with:
```
  multiCapabilities: [
        {
            browserName: 'chrome',
            shardTestFiles: true,
            maxInstances: 1,
        },
        {
            browserName: 'firefox',
            shardTestFiles: true,
            maxInstances: 1,
        }
    ]
```

**Comment by gandadil** [comment]
I have resolved my problem running the tests two times with different protractor.conf files. Each file is set to write the reports in different directory. Problem solved. Thanks all.
