### ISSUE TITLE
Feature: Add favicon

### ISSUE THREAD

**Issue by RonanC** [Evilweed/protractor-beautiful-reporter#157]
## Feature
Add favicon

## Why
When multiple tabs are open it can be frustrating to find the protractor screenshot report.

## Solution
If we have a favicon it'll make finding the correct tab much easier to spot.

**Comment by miller45** [comment]
Just released the version 1.2.9 with your favicon

**Comment by RonanC** [comment]
@miller45 Awesome! 👏
