### ISSUE TITLE
bootstrap.css missing

### ISSUE THREAD

**Issue by SDohle** [Evilweed/protractor-beautiful-reporter#16]
Hi,

the referenced bootstrap.css results in  a 404 error. 
Perhaps this is a good time to switch to bundeled assets?

**Comment by Evilweed** [comment]
[https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.1](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.1) Updated the CSS file link - if anyone has time to do PR with bundled CSS file - feel free to do it :)

**Comment by Evilweed** [comment]
@SDohle Please check [https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.4](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.4) - You can use **cssOverrideFile** to change css link to anything You want. If i will have more time i will make all assets be bundled.

**Comment by Evilweed** [comment]
@SDohle All assets are bundled since latest release.
