### ISSUE TITLE
Email report

### ISSUE THREAD

**Issue by savrik85** [Evilweed/protractor-beautiful-reporter#161]
Hey, thanks a lot for your great reporter.

Is there any way to send and read a report via email?

**Comment by rebajz** [comment]
try this:
"path_where_is_chrome\chrome.exe" --headless --disable-gpu --print-to-pdf=.\your_path\fileName.pdf --no-margins \.your_path\beautiful_reporter.html

**Comment by miller45** [comment]
Thanks @rebajz. I put a cmd example in the wiki [Print-report-to-pdf](https://github.com/Evilweed/protractor-beautiful-reporter/wiki/Print-report-to-pdf)

**Comment by miller45** [comment]
@savrik85 after pdf creating you can use a tool like blat.exe (windows) or many of the solutions on linux  (google "linux send email from bash" for that)

**Comment by rebajz** [comment]
colors in pdf - it is possible change css (assets/bootstrap.css) - section @media print

and for example add or change some other - for example hide top buttons and search input.

**Comment by miller45** [comment]
@savrik85 you could also just zip the contents of the folder and send that per email. The report usually works also when run from a filesystem.
