### ISSUE TITLE
It is impossible to open screenshots in generated report by mouseClick().

### ISSUE THREAD

**Issue by zhukovsv** [Evilweed/protractor-beautiful-reporter#170]
Trying to open screenshots in report by mouseClick:
- **Problem :** it is impossible to open screenshots in generated report by mouseClick().

1. "protractor-beautiful-reporter": "1.3.0"
2. **Google Chrome:** Version 76.0.3809.132 (Official Build) (64-bit)
3. **Console error:**
![image](https://user-images.githubusercontent.com/36186550/64171794-2c79be80-ce5c-11e9-9324-4cdf24c02c33.png)
4. **Error text:**
angular.min.js:110 Access to XMLHttpRequest at 'file:///C:/Users/.../Downloads/.../pbr-screenshot-modal.html' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

As I understand the problem appears after new functionality was added in 1.3.0 version. New functionality related to the next files:
![image](https://user-images.githubusercontent.com/36186550/64172169-06a0e980-ce5d-11e9-9224-33f90c748d2f.png)

Problem disappears if version is reversed to 1.2.9.

Is it possible to find problem solution with new functionality added in 1.3.0?

Regards, Sergei.

**Comment by miller45** [comment]
@zhukovsv First of all thank for the precise description :-)
It think it did not test opening the files with from a local folder, but with a temporary web server.
So i did not detect that it does not work when you open the report directly from file system.
Chrome just blocks ajax request for file protocol, so the report cannot load the pbr*modal* files if open directly from the files system.
While I search for a solution you can do the following in the meantime: 
- open a shell (e.g. cmd in windows)
- install a simple http server via `npm install -g http-server`.
- go into reports folder and type `http-server .`
- type the following url into chrome `http://localhost:8080

**Comment by miller45** [comment]
@zhukovsv I published a the version 1.3.1 which fixes this issue

**Comment by miller45** [comment]
Fixed in 1.3.1 and tested

**Comment by zhukovsv** [comment]
Thanks a lot. :-) 👍
