### ISSUE TITLE
All browsers besides Chrome, do not display the browerversion and platform type

### ISSUE THREAD

**Issue by dharnapahuja** [Evilweed/protractor-beautiful-reporter#172]
Hi,

I am running running tests on several browsers and browser versions and platforms. Once the report is generated, I see that the OS and platform columns are empty for Safari, Firefox etc, but works fine for Chrome. Why is that?

**Comment by miller45** [comment]
@dharnapahuja I will have a look at that later...

**Comment by miller45** [comment]
It looks like the attribute for platform was switched to platformName, and chrome is  still supporting the old property...I will fix this soon... 
After the fix you will notice that if you test with chrome the platform will be "Windows NT" and if you test with "Firefox"  it will be "windows". That is because the webdrivers are reporting the it differntly...

**Comment by miller45** [comment]
@dharnapahuja I released the version 1.3.2 just now... The os column should now also work with firefox

**Comment by miller45** [comment]
Does you selenium server run on windows or run locally?

Here is a example how the platform is "detected"
```javascript
const capabilities = await browser.getCapabilities();
let  os:  capabilities.get("platform") || capabilities.get("platformName") 
```
As you can see if the webdrivers return wrong values than there is nothing I can do about it...

**Comment by dharnapahuja** [comment]
<img width="724" alt="Screen Shot 2019-09-13 at 1 22 28 PM" src="https://user-images.githubusercontent.com/50838871/64881793-ad3d7500-d629-11e9-9697-25dff0c1c641.png">

**Comment by dharnapahuja** [comment]
I am using SauceLabs to run my tests. They are running on a server. The version and platform get displayed correctly for chrome, but not for Firefox

**Comment by miller45** [comment]
This browser version column is fixed in version v1.3.3

**Comment by dharnapahuja** [comment]
Hi, thank you for fixing that version number. It now works for Firefox as well. But the OS column still displays "ANY". Do you think that has something to do with selenium?

**Comment by miller45** [comment]
Yes when selenium/webdrivers drivers says "ANY" I cannot do anything. But on my local system it reported windows. Could also related to sauce labs...you can configure at lot of stuff there too.
