### ISSUE TITLE
How to display the data in "os" column and "browser" column

### ISSUE THREAD

**Issue by dharnapahuja** [Evilweed/protractor-beautiful-reporter#177]
I am generating a report for my tests and I notice that the browser name appears correctly, but no version number appears next to it. Also, the os column shows "ANY", whereas I specify the platform as macOS X. 

I want to be able to display this data for safari, chrome, edge and Firefox. How can I do that?

**Comment by miller45** [comment]
@dharnapahuja 
Does you selenium server run on windows or run locally?

Here is a example how the platform is "detected"
```javascript
const capabilities = await browser.getCapabilities();
let  os:  capabilities.get("platform") || capabilities.get("platformName") 
```
As you can see if the webdrivers return wrong values than there is nothing I can do about it...

About the browsers version there something I can do because it seems that sometimes the value is capabilities.get("version") and sometime capabilities.get("browserVersion")

**Comment by miller45** [comment]
I just noticed webdrivers differ in how they report the plaform e.g. firefox (geckodriver) reports "windows" and chrome reports "windows nt".

**Comment by dharnapahuja** [comment]
I run protractor locally but the tests run on sauce labs. If you could fix the browser for now, that would be great.

**Comment by dharnapahuja** [comment]
Also, is there no way logs can be supported on all other browsers as well? I know that logs are only working on Chrome as of now

**Comment by miller45** [comment]
@dharnapahuja I put up an own issue for browerslogs...may I find out how this can be done with firefox in the future

**Comment by miller45** [comment]
@dharnapahuja The issue with browser **version** is now fixed in version 1.3.3

**Comment by miller45** [comment]
@dharnapahuja I does not look good for having logs from firefox. The basic discussions are not finished in geckodriver repo: https://github.com/mozilla/geckodriver/issues/284

**Comment by miller45** [comment]
Browser version and OS is fixed (as far as its possible from reporters perspective)
