### ISSUE TITLE
Report screenshots and Log pop-ups were not being displayed in Chrome

### ISSUE THREAD

**Issue by pradeepv731** [Evilweed/protractor-beautiful-reporter#178]
Hi,
I have followed the tutorial and implemented the code as given, for a simple test. The report was generated and able to see the results. But, when clicked on the image icons no pop-up is being displayed. Also, the stack trace icons weren't working.
I have verified the same report in the Edge browser and it is working fine there.

I am using Win10 - 64bit, and chrome the latest version(77).

I had run the same code in my peer system and the report is working fine in that chrome browser, but both are using the same version of OS and Chrome.

Please find the files attached.

Confg file 
![Conf file](https://user-images.githubusercontent.com/55273475/64845904-f17c4580-d628-11e9-9bc8-0dde3bf1cc27.JPG)

pacakge file
![package file](https://user-images.githubusercontent.com/55273475/64845905-f214dc00-d628-11e9-80a6-7a135a54ad66.JPG)

Report files generated
![Report modules](https://user-images.githubusercontent.com/55273475/64845906-f214dc00-d628-11e9-9504-ffc39ff13be0.JPG)

Report 
![Report](https://user-images.githubusercontent.com/55273475/64845909-f214dc00-d628-11e9-92dc-f00df1786ffe.JPG)

Could you help me with this issue?

**Comment by miller45** [comment]
@pradeepv731 Make sure that you use at least version 1.3.1 the bug is fixed there...

**Comment by pradeepv731** [comment]
@miller45 Thank you so much. I have upgraded to the latest version and its working now..!

![image](https://user-images.githubusercontent.com/55273475/64936989-2c26ed80-d876-11e9-995e-bf7321f4fc4f.png)

![image](https://user-images.githubusercontent.com/55273475/64937033-49f45280-d876-11e9-83cc-171fc7658ba9.png)
