### ISSUE TITLE
Reference stylesheet the index.html template is not working.

### ISSUE THREAD

**Issue by anilparkin** [Evilweed/protractor-beautiful-reporter#18]
link rel="stylesheet" href="https://bootswatch.com/paper/bootstrap.css" crossorigin="anonymous">

The refrence hyperlink is not working.

The reports are plain ugly HTML with no styling.

![image](https://user-images.githubusercontent.com/32290829/32374767-0c99eb2c-c0c5-11e7-9fcb-d91898c4b540.png)

**Comment by ViktorMikhalkin** [comment]
Have got the similar issue today.
![broken-report](https://user-images.githubusercontent.com/9029022/32389152-877c485a-c0d2-11e7-83ec-e8f8c1b3b6bc.png)

**Comment by qanl** [comment]
Similar problem here as well.

**Comment by svspratap** [comment]
Having the same problem.

**Comment by Evilweed** [comment]
[https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.1](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.1) Updated the CSS link

**Comment by ViktorMikhalkin** [comment]
Thank you! This works now as expected.

**Comment by Evilweed** [comment]
@anilparkin @ViktorMikhalkin @qanl @VenkatSaripilli All assets are bundled since latest release.
