### ISSUE TITLE
Improvement: Show result for each expectation/ assertion in the spec

### ISSUE THREAD

**Issue by Sumejja** [Evilweed/protractor-beautiful-reporter#19]
Hi,
Thank you for publishing such a beautiful reporter.
I am wondering if it is possible to include summary / result for each expectation within the spec, not only for the spec as a whole? 
This is how it looks like with [protractor-screenshoter-plugin](https://www.npmjs.com/package/protractor-screenshoter-plugin). It has an expandable panel that contains all the verifications that we made in the test, which is really useful.
![image](https://user-images.githubusercontent.com/9977979/32557916-d6a6794e-c4a3-11e7-8bef-9c6351357026.png)

**Comment by bongosway** [comment]
@Evilweed I am few months in to javascript, but willing to take this one. 
Is there a chance you have a CONTRIBUTING.md file somewhere, that can guide me?

Reporter is beautiful. I have actually adopted it at work. so I want to help. Thanks

**Comment by bongosway** [comment]
@Sumejja Please give me some specifics. I was not able to install protractor-screenshoter-plugin properly, so could not check it out.
A mockup or something more descriptive would be nice.
A sample summary text would be appreciated.

Thanks

**Comment by Evilweed** [comment]
@bongosway I will create this doc when I will have some spare time. Do You have any questions before You start working on that?

**Comment by bongosway** [comment]
PR #38 opened. Thanks

**Comment by Evilweed** [comment]
We have decided that this is not in line with best practice of writing one expect per test case so for now i'm closing this one.
