### ISSUE TITLE
Improvment : Allow offline consultation

### ISSUE THREAD

**Issue by clementbrunel** [Evilweed/protractor-beautiful-reporter#2]
Hello, me again.

As a proposal, it should be cool if you include a flag to generate offline report ( with angular / jquery / bootstrap )  not included with cdn but with local files.

Regards.

**Comment by Evilweed** [comment]
If You would like to do a Pull Request - feel free to do it. If not I will do this in spare time. Thanks for the input!

**Comment by Evilweed** [comment]
@clementbrunel Please check [https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.4](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.4) - You can use **cssOverrideFile** to change css link to anything You want. If i will have more time i will try to make all files be stored locally.

**Comment by clementbrunel** [comment]
Thank you, this should do a part of the job.
Sorry, don't have time to work on this project anymore.
But i kept my star on your project for my next js app :)

**Comment by Evilweed** [comment]
@clementbrunel Fixed. All assets are bundled since latest release.
