### ISSUE TITLE
Require line reports error on launching protractor

### ISSUE THREAD

**Issue by sepa-joe** [Evilweed/protractor-beautiful-reporter#20]
Hey,

I updated my webdriver-manager and now when I try to launch any protractor tests I get the following:
```
SyntaxError: Unexpected token (
...
..
..
  at Object.<anonymous> (C:\Users\a\Desktop\protractor\batshit.js:1:82)
```

Line 1 is showing:
`var HtmlReporter = require('protractor-beautiful-reporter');`

I can't see what is wrong with it

If I change the line and comment it use the standard HTML report it all works fine.

Anyone got any additional ideas?

**Comment by sepa-joe** [comment]
Ran npm i protractor-beautiful-reporter - which reports updating to 0.5.3
Other versions
@angular/cli: 1.4.9
node: 6.11.4
os: win32 x64

**Comment by Evilweed** [comment]
Version >0.5.1 requires node 8+. I had hard time figuring out how to compile it to lower node version.

**Comment by sepa-joe** [comment]
I'll try upgrading - though it seems the easiest way to upgrade is to reinstall on windows...

**Comment by sepa-joe** [comment]
@Evilweed - many thanks.  Actually sorted another issue I was having.  But updated to 8.9.1 and all working great again.  Bit of a pain having to download newest node as couldn't find a way to update installed version (on windows anyway) - but that's a node issue.  I'll close this issues if I am able to :)
