### ISSUE TITLE
Is this still maintained? 

### ISSUE THREAD

**Issue by johnnguyen0215** [Evilweed/protractor-beautiful-reporter#204]
@miller45 

Hi I was wondering if this repo is still maintained. I emailed the original author at the bottom of the README but they mentioned that they have passed this project over to you! I couldn't find your contact anywhere, so hoping this catches your eye.

Thanks!

**Comment by miller45** [comment]
Hi @johnnguyen0215 i am currently not active, but do you have a specific request or do you want help the project?

**Comment by gituser-21** [comment]
Hello, 
I am trying to get this tool working with protractor/cucumber. Does it only work with Jasmine ? Error is as below:

[12:29:47] E/launcher - Error: TypeError: jasmine.getEnv is not a function

var HtmlReporter = require('protractor-beautiful-reporter');

//Is this required?
 //var jasmine = require ('jasmine-core');
//var Jasmine = require ('jasmine');
//var jasmine = new Jasmine();

exports.config = {
framework: custom,
    frameworkPath: require.resolve('protractor-cucumber-framework'),

onPrepare: function () {
        browser.manage().window().setSize(1600, 1050);
        browser.waitForAngularEnabled(false);
        let hrep = new HtmlReporter({
            baseDirectory: 'beaut/screenshots',
            screenshotsSubfolder: 'images',
            jsonsSubfolder: 'jsons',
            takeScreenShotsOnlyForFailedSpecs: true,
            docTitle: 'E2e tests',
            gatherBrowserLogs: true,
            clientDefaults:{
                columnSettings:{
                    //displayTime:true,
                    //displayBrowser:false,
                    //displaySessionId:false,
                    //displayOS:false,
                    inlineScreenshots:true, 
                    warningTime: 1000,
                    dangerTime: 1500,
                    showTotalDurationIn: "belowHeader", 
                    totalDurationFormat: "hms"     
                }
             },
            sortFunction: function sortFunction(a: any, b: any) {
                if (a.instanceId < b.instanceId) return -1;
                else if (a.instanceId > b.instanceId) return 1;
             
                if (a.timestamp < b.timestamp) return -1;
                else if (a.timestamp > b.timestamp) return 1;
             
                return 0;
            }
         });
         //var jasmine = require ('jasmine-core');
         jasmine.getEnv().addReporter(
            hrep.getJasmine2Reporter()
          );
        //browser.ignoreSynchronization = true;
    } //on prepare
} // exports.config

**Comment by miller45** [comment]
@johnnguyen0215 Yes sorry. The report code is relying on  jasmine functionality. It is a reporting plugin for jasmine.

**Comment by gituser-21** [comment]
Actually, it's @gituser-21  but thank you ! @miller45
