### ISSUE TITLE
failed loading configuration file

### ISSUE THREAD

**Issue by harvishan** [Evilweed/protractor-beautiful-reporter#21]
I'm getting following error when running the test.

[13:04:38] E/configParser - Error code: 105
     [exec] [13:04:38] E/configParser - Error message: failed loading configuration file /Users/click/Git/clickhq-v2/frontend/test/e2e/conf.js
     [exec] [13:04:38] E/configParser - /Users/click/Git/clickhq-v2/frontend/node_modules/protractor-beautiful-reporter/index.js:205
     [exec]         **this._addTaskToFlow(async () => this._suiteNames.push(result.description));**

Please kindly fix ASAP. Thanks

**Comment by anilparkin** [comment]
Facing same issue. It broke all my automation tests in production.

/node_modules/protractor-beautiful-reporter/index.js:205
        this._addTaskToFlow(async () => this._suiteNames.push(result.description));

**Comment by anilparkin** [comment]
Any update on the above issue ??

**Comment by Evilweed** [comment]
Please update node to version 8+, or downgrade reporter version. For now Latest Node version is supported.
