### ISSUE TITLE
After report is created, the html and javascript file data is deleted. Shows 0kb

### ISSUE THREAD

**Issue by VenkatSaripilli** [Evilweed/protractor-beautiful-reporter#22]
While the tests are running I can open and see the html file. But towards the end of the tests, the html and javascript file content is deleted and shows 0 KB files.

![image](https://user-images.githubusercontent.com/33403257/32929865-de3c2e74-cbbf-11e7-89b0-baea9708dbe2.png)

**Comment by Evilweed** [comment]
My guess is that You enabled test sharding:

> shardTestFiles: true

But You forgot to set the:

> preserveDirectory: true,

If You won't change this flag to true then every browser will delete tests form previous browsers.

Let me know if this was the case.

**Comment by VenkatSaripilli** [comment]
Thanks @Evilweed, I tested it with both shardTestFiles and preserveDirectory set to true, but the issue did not go away. However I tried to check the other properties and strangely when I set the takeScreenShotsOnlyForFailedSpec: true, everything worked file. If I set it to false, then the problem keeps coming.

**Comment by Evilweed** [comment]
@VenkatSaripilli I've tried with *takeScreenShotsOnlyForFailedSpec* set to *false* but everything worked properly - files were generated.

**Comment by VenkatSaripilli** [comment]
@Evilweed. it is working for me now. The issue can be closed

**Comment by Evilweed** [comment]
@VenkatSaripilli - did You find what was causing the problem? Could You send me the faulty config file? If it is an issue it's better to fix it :)

**Comment by Evilweed** [comment]
@VenkatSaripilli please reopen if this reoccurs.
