### ISSUE TITLE
docTitle option not setting title of the report

### ISSUE THREAD

**Issue by sepa-joe** [Evilweed/protractor-beautiful-reporter#24]
When I use
`docTitle: 'SG Alpha 2',`
I am not seeing the name of the report change.  The title still shows as "Protractor Screenshot Report" and the heading in the document says "Test Results" - am I mistaken as I would have expected one of those to change?

**Comment by Evilweed** [comment]
@sepa-joe Fixed in [https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.5](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.5)
