### ISSUE TITLE
Not able to create a dynamic reporting path(which will include browser name ,Date time etc) for multi-capabilities

### ISSUE THREAD

**Issue by Tehaseen** [Evilweed/protractor-beautiful-reporter#26]
**Observation:**  
In the  **onPrepare()** function when we define path for report in the **baseDirectory** , i am not able get the value of browser name . Refer the below code

 onPrepare: function() {     
      browser.getCapabilities().then(function(caps){
      console.log('THe browser name '+ browser.browserName);
      browser.browserName= caps.get('browserName'); 
    });   
      jasmine.getEnv().addReporter(new HtmlReporter({
        baseDirectory: '../../../../../../Test/'+**browser.browserName**,
        pathBuilder: function pathBuilder(spec, descriptions, results) {
          // Return '<browser>/<specname>' as path for screenshots:
          // Example: 'firefox/list-should work'.
        return path.join( descriptions) ;},
        screenshotsSubfolder: 'ScreenShots',        
        jsonsSubfolder: 'Jsons',
        docTitle: 'Report',
        docName: 'Report.html',
        preserveDirectory: false
     }).getJasmine2Reporter()); 
    }

We require to create a dynamic path because multicapabilities launches on different browser . So different browser will require different path .

In the above code ,
 "browser.browserName" in console log is returning a promise .
 "browser.browserName" in the baseDirectory is returning a string "undefined".

tried using path builder property , but this property builds path only for screen shot .

**Expected Result :** 
Generate a dynamic reporting path based on browser name 
So that when we use this plugin for multi-capabilities , different browser will have different report

Thanks in Advance :)

**Comment by miller45** [comment]
Maybe you can find a solution here: https://github.com/angular/protractor/issues/1938 
scroll to the bottom there...

**Comment by Evilweed** [comment]
**browser.browserName = caps.get('browserName');** returns a promise so in order to use this information You need to unwrap it...

```
browser.browserName = caps.get('browserName');

browser.browserName.then((name) => {
    jasmine.getEnv().addReporter(new HtmlReporter({
    baseDirectory: '../../../../../../Test/'+name,
    ...
    }).getJasmine2Reporter());
})

```

**Comment by Tehaseen** [comment]
Hi Evilweed, 
Thanks for the reply , but when i try to unwrap promise i am getting the below error.
 **"TypeError: browser.browserName.then is not a function"**

Please find the below **onPrepare** function

   _onPrepare: function() {
        browser.getCapabilities().then(function(caps){
        console.log('THe browser name '+ browser.browserName);
        browser.browserName= caps.get('browserName');        

        browser.browserName.then(function(name) {
        jasmine.getEnv().addReporter(new HtmlReporter({
        baseDirectory: '../../../../../../Test/'+name,
        pathBuilder: function pathBuilder(spec, descriptions, results) {
        // Return '/' as path for screenshots:
        // Example: 'firefox/list-should work'.
        return path.join( descriptions) ;},
        screenshotsSubfolder: 'ScreenShots',
        jsonsSubfolder: 'Jsons',
        docTitle: 'Report',
        docName: 'Report.html',
        preserveDirectory: false
        }).getJasmine2Reporter());
      });
    });
        }_
      
**Expected Result:** Generate a dynamic reporting path based on browser name
So that when we use this plugin for multi-capabilities , different browser will have different report

Many Thanks in Advance
