### ISSUE TITLE
Sort "it" into "describe" by execution order.

### ISSUE THREAD

**Issue by pfoucray** [Evilweed/protractor-beautiful-reporter#27]
Hi,

thanks for your report, it's very nice and make my tests results more clear !

Right now, the tests are sorted by alphabetical order /
Ex

- Should a

- should b...

Could you add the timestamp of the execution into the html result page and let us be able to sort by this timestamp ?

Thx in advance,
regarde,
PF

**Comment by Evilweed** [comment]
@pfoucray @bvasilchik How it should be sorted if we run tests parallely on many browsers?

Sort **"describes"** by alphabetical order, and then in those sort **"it's"** using timestamp?

**Comment by pfoucray** [comment]
Hi @Evilweed,

thx for the reply.
In my case I'm using Jamsine in a little framework of mine, that describes scenarios (functional, business e2e tests)
So, in my words, "Describe" is a Test Case, "It" is a step (whil in Jasmine, "describe" is a test Suite and "It" is a Test Cases). To me, the order of execution of the "it" is mandatory.

So I'm trying to find a way to sort the it into a describe by execution order.
I'm a bad developer (not a real developer actualy), so I tried to use the metadata builder to customize the name of the "it", inserting a number that would be generated when it is executed, but so far no success...
Looking for something like this 
"describe"
     01 - should z
     02 - should a

A good solution would then be to get a time stamp of execution into the Json files so that HTML report would let us Sort everything by execution time !

Hope it's more clear,

regards,
PF

**Comment by bvasilchik** [comment]
@pfoucray I have also tried to use the metadata builder to change the names of the describes. I can change the pass or failed the OS and the session id and most all the other parameters but I can't get the description to change. If you ever figure it out I would love to know

**Comment by VenkatSaripilli** [comment]
These are great reports. Thanks for the developer.

I face same problem as mentioned here, with my tests. I have the following structure and executed in the order Suite 1 then Suite 2

### ## Suite 1                                                                                
Describe 1 **xyz** (level1)                                                             
   Describe 2 **gef** (level2)                                                                  
        it 1...                                                                                   
        it 2....                                                          
        it 3...
   Describe 3 **bcd** (level 2)
       it 4...
       it 5
       it 6 ... 
end suite 1

### ## Suite 2
Describe 4 **abc** (level 1)
    it 7
    it 8
    it 9
end suite 2

## The report is as follows.
  Describe 4 **abc**
     it 8
     it 9
     it 7
  Describe  1 **xyz** (level 1)
      Describe 3 **bcd** (level 2)
             it 5... 
             it 4..
             it 6..
       Describe 2 **gef** (level 2)
            it 3..
            it 1..
            it 2..

Everything is sorted in alphabetical order, and this is confusing as the order is not what the tests have been executed.

What I like is to display the report sorted with ascending time as my steps got executed. If there is a way to add a sort feature to sort the by time or sort in order they have been executed, that would be great. 

Thanks

**Comment by pfoucray** [comment]
@bvasilchik, I think the two options, without asking the developper is

- name your describes and it with numbers in front. In my case it's not possible because they are not always used in the same order as I'm making libraries of "it"
- modify the code of the module. there is a function that makes an array of the descriptions and it then it concatenates it into the json builder like this "describe|it" and finaly the html builder "understands there are 2 lvls (with "|" as separator).
which is why the solution I propose is to add a time stamp as parameter in the report, and upgarde the Front part to let us "sort by" "timestamp"... or something like that.
Not sure it's clear :/

**Comment by Evilweed** [comment]
@pfoucray @bvasilchik @VenkatSaripilli I've added timestamp to the latest version [https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.6](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.6) You can use it to tweak sorting algorithm. If any of You will do this - please share, I don't have time to implement it right now.

**Sorting is done in app.js (line 134):**
```
    this.init = function () {
        this.results = results.sort(function(a, b) {
            if (a.cachedName == null) { a.cachedName = a.description.split('|').reverse().join() };
            if (b.cachedName == null) { b.cachedName = b.description.split('|').reverse().join() };

            var first = a.cachedName;
            var second = b.cachedName;

            return first.localeCompare(second)
        });
    };
```

And this is how JSON output looks like right now:
```
{
    "description":"should add a todo|todo list|angularjs homepage",
    "passed":true,
    "pending":false,
    "os":"Mac OS X",
    "browser":{"name":"chrome","version":"63.0.3239.84"},
    "message":"Passed.",
    "trace":"",
    "browserLogs":[],
    "timestamp":1512748015457,
    "duration":2568
}
```

Timestamp was created by new Date().getTime().

Cheers :)

**Comment by pfoucray** [comment]
For my part, I don't realy have the skills to do so, but will stay aware of if the feature is finished later on. Thanks anyways for the 1st step :)

**Comment by heetred** [comment]
Following changes in the code worked for me. This will always sort the results in execution order. 

 this.init = function () {
        this.results = results.sort(function(a, b) {
            var first = a.timestamp;
            var second = b.timestamp;

            if(first < second) return -1
            else return 1
        });
    };

If you want to add an option to sort on the basis of execution or default sort, I can take up the work.

**Comment by Evilweed** [comment]
@heetred - go for it :) If You will do Pull Request i can merge it.

**Comment by VenkatSaripilli** [comment]
@heetred. Thank you. That worked for me.

**Comment by ViktorMikhalkin** [comment]
@heetred Thank you! Will be waiting for your pull request.

**Comment by pfoucray** [comment]
Yep same, I changed the code localy, but I'll be looking for the new version !!
Thx to everyone here :)

**Comment by Evilweed** [comment]
@pfoucray @bvasilchik @VenkatSaripilli @heetred Since [v0.5.8](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.8) You can override default sort function :) Have fun!

```javascript
new HtmlReporter({
   baseDirectory: 'tmp/screenshots'
   , sortFunction: function sortFunction(a, b) {
         if (a.cachedBase === undefined) {
             var aTemp = a.description.split('|').reverse();
             a.cachedBase = aTemp.slice(0).slice(0,-1);
             a.cachedName = aTemp.slice(0).join('');
         };
         if (b.cachedBase === undefined) {
             var bTemp = b.description.split('|').reverse();
             b.cachedBase = bTemp.slice(0).slice(0,-1);
             b.cachedName = bTemp.slice(0).join('');
         };
    
         var firstBase = a.cachedBase;
         var secondBase = b.cachedBase;
    
         for (var i = 0; i < firstBase.length || i < secondBase.length; i++) {
    
             if (firstBase[i] === undefined) { return -1; }
             if (secondBase[i] === undefined) { return 1; }
             if (firstBase[i].localeCompare(secondBase[i]) === 0) { continue; }
             return firstBase[i].localeCompare(secondBase[i]);
         }
    
         var firstTimestamp = a.timestamp;
         var secondTimestamp = b.timestamp;
    
         if(firstTimestamp < secondTimestamp) return -1;
         else return 1;
     }
});
```
