### ISSUE TITLE
Include specname in the description of the report?

### ISSUE THREAD

**Issue by bvasilchik** [Evilweed/protractor-beautiful-reporter#28]
Sorry if this is already available. I thought it was achievable by  the metaDataBuilder function but I can't even seem to get that to work unless I have misunderstood it's use. 

I tried the below as a test to see if it would change the description to Testing. My goal is to keep the current description which I believe is based of the name of the describe block but add the specfilename to that description so I can know which filename it belonged to. any help is appreciated. 

<img width="1387" alt="screen shot 2017-11-29 at 5 13 48 pm" src="https://user-images.githubusercontent.com/10767745/33401867-cc1cda8c-d528-11e7-8000-fb1e463ddfd3.png">

```
    var path = require('path');
    var reporter = new HtmlReporter({
      baseDirectory: 'tmp/screenshots',
      pathBuilder: function pathBuilder(spec, descriptions, results, capabilities) {
        // Return '<browser>/<specname>' as path for screenshots:
        // Example: 'firefox/list-should work'
        return path.join(browser.browserName + process.env.TAG, descriptions.join('-'));
      },
      metaDataBuilder: function metaDataBuilder(spec, descriptions, results, capabilities) {
          // Return the description of the spec and if it has passed or not:
          return {
             description: 'Testing',
             passed: results.passed()
          };
      },
      takeScreenShotsOnlyForFailedSpecs: true,

    });
    // Add a screenshot reporter and store screenshots to `/tmp/screenshots`:
    jasmine.getEnv().addReporter(reporter.getJasmine2Reporter());
```

**Comment by Evilweed** [comment]
If You are using Jasmine2 then You need to use **jasmine2MetaDataBuilder**.

You can extract specs like that (I don't remember how to extract current spec).
```
    browser.getProcessedConfig().then(function(config) {
        let specs = config.specs;
```

**Comment by bvasilchik** [comment]
thank you for your response it seems modifying the description doesn't make a difference. I did a test and if I change the OS it does take in what I pass the function. I am using jasmine2 and here is the below code. 


![screen shot 2017-12-04 at 11 54 54 am](https://user-images.githubusercontent.com/10767745/33565176-64dcfdd2-d8ea-11e7-8df5-e1703b610623.png)



`
    jasmine.getEnv().addReporter(new HtmlReporter({
        preserveDirectory: false,
        takeScreenShotsOnlyForFailedSpecs: true,
        screenshotsSubfolder: 'images',
        jsonsSubfolder: 'jsons',
        baseDirectory: 'reports-tmp',

        pathBuilder: function pathBuilder(spec, descriptions, results, capabilities) {
          // Return '<30-12-2016>/<browser>/<specname>' as path for screenshots:
          // Example: '30-12-2016/firefox/list-should work'.
          var currentDate = new Date(),
              day = currentDate.getDate(),
              month = currentDate.getMonth() + 1,
              year = currentDate.getFullYear();

          var validDescriptions = descriptions.map(function (description) {
              return description.replace('/', '@');
          });

          return path.join(
              process.env.TAG,
              day + "-" + month + "-" + year,
              validDescriptions.join('-'));
        },
        jasmine2MetaDataBuilder: function metaDataBuilder(spec, descriptions, results, capabilities) {
          // Return the description of the spec and if it has passed or not:
          return {
            description: "Testing",//descriptions.join(' '),
            passed: results.status === 'passed',
            pending: results.status === 'pending' || results.status === 'disabled',
            os: 'Testing',//capabilities.get('platform'),
            sessionId: capabilities.get('webdriver.remote.sessionid'),
            browser: {
                name: capabilities.get('browserName'),
                version: capabilities.get('version')
            }
          };
        }
    }).getJasmine2Reporter());
`
