### ISSUE TITLE
CSS not loaded: I have fix, please read

### ISSUE THREAD

**Issue by schwarcu** [Evilweed/protractor-beautiful-reporter#29]
Website bootswatch have update their "repository" and now themes for bootstrap 3.x.x are found under different URL. Right now test report has no css because of wrong stylesheet href.
Please change it to:
`<link rel="stylesheet" href="https://bootswatch.com/3/paper/bootstrap.css" crossorigin="anonymous">`

**Comment by nicolasabric** [comment]
Just stumble upon this one as well. I have fixed it locally by adding the cssOverrideFile property to my config. Here is my working conf for reference :

`new HtmlReporter({
      preserveDirectory: false,
      takeScreenShotsOnlyForFailedSpecs: false,
      screenshotsSubfolder: 'images',
      jsonsSubfolder: 'jsons',
      baseDirectory: './dist/tests/protractor',
      docName: 'index.html',
      **cssOverrideFile: 'https://bootswatch.com/3/paper/bootstrap.min.css'**
    }`

Last line is what I'va added.

**Comment by schwarcu** [comment]
Doesn't work for me.  Old url still appears :(

**Comment by nicolasabric** [comment]
Which version are you using? On my side I add to update to the latest version 0.5.3.

**Comment by schwarcu** [comment]
I also have 0.5.3

**Comment by nicolasabric** [comment]
Could you share your HtmlReporter config I will try with it

**Comment by schwarcu** [comment]
I have manually updated the HTML template. Code on github is fixed but somehow updating through npm does not make any effect

**Comment by Evilweed** [comment]
@schwarcu as You mentioned - version 0.5.3 has proper and working URL.

But i've noticed that css override was not implemented after code refactor so I've fixed it now.
Please check [https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.4](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.4) - You can use **cssOverrideFile** to change css link to anything You want.

**Comment by schwarcu** [comment]
@Evilweed dzięki ;)

**Comment by Evilweed** [comment]
@schwarcu @nicolasabric Fixed. All assets are bundled since latest release.

**Comment by schwarcu** [comment]
Thanks!
