### ISSUE TITLE
Report does not generate

### ISSUE THREAD

**Issue by perwezalamnewscorp** [Evilweed/protractor-beautiful-reporter#3]
I have followed the instruction mentioned in the doc for generating the report, But I am not seeing any in my project directory.

Do I need to follow some other steps which is not mentioned in the doc.

Can you please provide me the solution to make. I am not getting any error.

I have done the npm installaltion

My Package.jason looks like this
=================================

{
  "name": "protractor",
  "version": "1.0.0",
  "description": "",
  "main": "conf.js",
  "scripts": {
    "start": "babel-node test/TestScripts.js —presets es2015,stage-2",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mkdirp": "~0.3.5",
    "underscore": "~1.6.0"
  },
  "devDependencies": {
    "babel-core": "^6.17.0",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-stage-1": "^6.16.0",
    "babel-runtime": "^6.11.6",
    "protractor-beautiful-reporter": "^0.4.5",
    "protractor-html-hierarchical-reporter": "^1.6.0",
    "protractor-html-screenshot-reporter": "0.0.21",
    "protractor-jasmine2-html-reporter": "0.0.7"
  }
}

conf.js looks like this
=================

require('babel-core/register');
var HtmlReporter = require('protractor-beautiful-reporter');
var path = require('path');
exports.config = {
  directConnect: true,

  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'chrome'
  },

  // Framework to use. Jasmine is recommended.
  framework: 'jasmine',

  // Spec patterns are relative to the current working directory when
  // protractor is called.
  specs: ['test/TestScripts.js'],
  allScriptsTimeout: 120000,
  getPageTimeout: 120000,
  jasmineNodeOpts: {
    defaultTimeoutInterval: 120000
},

    rootElement: 'body',
   // your config here ... 
 
   onPrepare: function() {
      // Add a screenshot reporter and store screenshots to `/tmp/screenshots`: 
      jasmine.getEnv().addReporter(new HtmlReporter({
         baseDirectory: '/test'
      }).getJasmine2Reporter());
   }
  // Options to be passed to Jasmine.
  

};

**Comment by clementbrunel** [comment]
What is the ouput in you console?
Surprise with the part : 
`"test": "echo "Error: no test specified" && exit 1"`

**Comment by Evilweed** [comment]
You don't have "protractor" in your devDependencies so i can't know what version do You use and what Jasmine do You use.

For now replace:
`baseDirectory: '/test'`
With:
`baseDirectory: 'test'`

If it does not help replace:
`specs: ['test/TestScripts.js'],`
With:
`specs: ['./*/*.js'],`

Next time please provide Protractor and Jasmine versions and console log.

**Comment by perwezalamnewscorp** [comment]
Its working after replacing the baseDirectory.

baseDirectory: '/test'
With:
baseDirectory: 'test'


Thank you so much for your help. Hence I am closing this issue.
