### ISSUE TITLE
Question: blocked scripts

### ISSUE THREAD

**Issue by sepa-joe** [Evilweed/protractor-beautiful-reporter#30]
Question - so I am deploying the reports via Jenkins.  And so far I can see the report is being produced along with a bunch of screenshots.  However when I try to load the report, I get the following:

![report](https://user-images.githubusercontent.com/32637456/33949191-d44a552e-e020-11e7-89fa-952349da7aaf.PNG)

I firstly copied the report off the machine and put it on my own to test.  This worked as expected.

So opened up the console and saw the following:

> Content Security Policy: The page’s settings blocked the loading of a resource at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js (“script-src http://dskvm4981-iis:8080 'unsafe-inline' 'unsafe-eval'”).

a quick google shows there is some html which can be added to the meta to get round this:  

> <meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' http://www.google.com">

No problem, I thought I could go to the index.html page located in appdata/roaming/npm/node_modules/protractor-beautiful-reporter/lib and modify the html file and any new reports would have this line.  However it isn't.  Is there any place else I can do the above - or is there an option when generating the report to override content security policy?

**Comment by Tehaseen** [comment]
Hi , try opening the report with chrome browser . It will work

**Comment by Evilweed** [comment]
@sepa-joe Fixed. All assets are bundled since latest release.

**Comment by sepa-joe** [comment]
@Evilweed Still having a few issues with this - while the app.js has been bundled, Jenkins is still blocking the angular.js file in the reporter.  I don't actually know how to unblock this, so as a temp workaround could you tell me where if I can change it so it points to a local angular (and I'd just download it and store it on the same box?)
