### ISSUE TITLE
Takes a long time to generate report with lots of pending specs

### ISSUE THREAD

**Issue by bloof-bb** [Evilweed/protractor-beautiful-reporter#33]
Hello,

In this case, with about 950 tests not running (because one suite was focused with an `fdescribe`) it takes nearly 30 seconds at the end of the run to generate the report. It appears a json file is being made for each one.

I'd imagine the way to make this faster is either an option to not report on pending specs at all, or to not have to do so much I/O when going through a lot of pending specs.

**Comment by Evilweed** [comment]
Added in latest release.
