### ISSUE TITLE
Missing glyphs in generated report

### ISSUE THREAD

**Issue by Evilweed** [Evilweed/protractor-beautiful-reporter#35]
Missing glyphs in generated report.
Forgot to bundle fonts.

![Missing fonts](https://i.imgur.com/IXZOZI5.png)

**Comment by aboudard** [comment]
Hi,
If you point me the direction of where reports and resources are generated in your sources, I could help :)

**Comment by aboudard** [comment]
Ok, I'll try that when I have time :)
Thanks for the hints.

**Comment by aboudard** [comment]
Hey @Evilweed !

What would you prefer ?
- keep all files copied in the root folder including the fonts >> alter bootstrap.css @font-face declaration
or
- keep the bootstrap @font-face relative path ../fonts/glyphicons... >> create the /fonts/ folder in the utils.js

I see no major difference here in my opinion.

**Comment by Evilweed** [comment]
@aboudard - lets keep the bootstrap @font-face relative path

**Comment by aboudard** [comment]
Hey @Evilweed 
I tried a few things, ending up with a new mkdirp for the fonts, but in the original bootstrap distrib, the css files are in a css folder, hence the ../fonts/glyph-blabla.ttf ... 

Then maybe we should keep the original folder structure.

But that's just a detail, since you are right about the need for a unique operation, otherwise we attempt the creation of folders and copy of the files at every iteration.
Cheers

**Comment by SDohle** [comment]
Hi,
we fixed the missing Icons by adding the missing fonts and copying the assets and fonts folder.
Perhaps this is suitable for you all?

I pushed our code changes in Pullrequest #42. Please take a look @Evilweed @aboudard

**Comment by aboudard** [comment]
Hi @SDohle 
Well are you sure you commited all the code ?
Because the generated report.html doesn't link to /assets/*.js files, so all js are broken - if I tested your code correctly.
Should you not alter the index.html file too ?

**Comment by SDohle** [comment]
Hi,
Thanks for the hint @aboudard. I just forgot to include the index.html in my commit.
Sorry! I've just updated the PR.

**Comment by Evilweed** [comment]
Fixed in latest [version v1.1.2](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v1.1.2). @SDohle Thanks for PR :)

**Comment by aboudard** [comment]
Excellent :) @SDohle
