### ISSUE TITLE
Sowing inconsistent specs count intermittently

### ISSUE THREAD

**Issue by perwezalamnewscorp** [Evilweed/protractor-beautiful-reporter#4]
I have two test1-spec.js and test2-spec.js file. I have spotted wrong specs  count showing on the report When I ran them .

Issue1# I ran both file and it showing the less count by 1. It showing all spec-1 count into the report as compared to the console count.

Issue2: When I disabled some test suite(xdescribe) and reran the test suite. Then showing very strange count. It does not match with the previous report . Again I ran the test suite then it shows the same result as show very first time (less by 1). 

for second issue - Is it not cleaning the directory or the test report  before generating the new one ?

Step to reproduce the issue
----------------------------

1.Run the test from multiple test-specs.js files and see the test spec count
2.Now disable some test suite specs (xdescribe).
3.Re run the test (All specs file).
4.See the specs count into the newly generated report. It shows the wrong count.
5.Again re run it. It shows the different count. 

Expected behavior : It should clean the previous report data and generate the clean report with correct count.It think it should be the default behavior .

Do you want any data for this issue ,As It does not generate any error or console message for this ?

**Comment by perwezalamnewscorp** [comment]
I have four screen shot below, In the screen shot you see different specs count. This is the report the same number specs run all the time. 

Note- I have disbaled the test suite like this (xdescribe) which I do not want run . This should be captured as pending status.

My question is - Why different specs count display in each run ?


<img width="1257" alt="screen shot 2017-05-04 at 3 29 07 pm" src="https://cloud.githubusercontent.com/assets/19994714/25699722/1099a4d8-30e2-11e7-89de-f41dc043e5f5.png">
<img width="1265" alt="screen shot 2017-05-04 at 3 33 39 pm" src="https://cloud.githubusercontent.com/assets/19994714/25699723/109bce8e-30e2-11e7-9b56-53acd5e84d46.png">
<img width="1263" alt="screen shot 2017-05-04 at 3 37 01 pm" src="https://cloud.githubusercontent.com/assets/19994714/25699724/109beb08-30e2-11e7-8dc1-d510c0a25cd2.png">
<img width="1244" alt="screen shot 2017-05-04 at 3 53 58 pm" src="https://cloud.githubusercontent.com/assets/19994714/25699725/109c1b6e-30e2-11e7-8f47-b69c18dec4af.png">

**Comment by perwezalamnewscorp** [comment]
Version of the tool that I used for generating rpeort

Protarctor - Version 5.1.1
Jasmine     -version  2.6.0

**Comment by perwezalamnewscorp** [comment]
I  identified the issue and it can be easily reporduced

Steps are
1.Run the below code without any change and It generate the report which does not show any pending specs detail. because last suite has been disabled (xdescribe).

2.Now disable the first child suite and enable the last child suite, It generate the report with all the specs details . it shows the pending specs details too.

Why like this behavior ? Is it expected ?


describe('',function(){


Please execute the following specs given below to reproduce this issue.


describe('Parent Test suite',function(){



        describe('Child testsuite 1',function(){

           it('Test 1',function(){
            expect(true).toBeTruthy();

           });

           t('Test 2',function(){
            expect(false).toBeTruthy();

           });
        });

        xdescribe('Child testsuite 2',function(){

           it('Test 1',function(){
            expect(true).toBeTruthy();

           });

           t('Test 2',function(){
            expect(false).toBeTruthy();

           });
        });


      });

**Comment by perwezalamnewscorp** [comment]
Regarding Issue1# , It show less spec count.


If only one test spec is run then , It does not generate the test report itself.If it is more than 1 test spec then only it generate the test report.


For Example (Run this below specs, It does not generate the report)

 describe('INCA Home Page Text verification', function() {


      it('Hello World1',function(){

      	 expect("hello").toBe(true);

          });

      });

**Comment by Evilweed** [comment]
**Issue 2:** 

There is an option to preserve directory before each run. If it's not set to false then each run will prepend data to previous XML and display one report with 2 runs.

`preserveDirectory: false,`

**Issue 1:**

I will try to check it in my spare time.

**Comment by Evilweed** [comment]
**Issue 1:**
Last "it" is not prepended to JSON file due to error in gathering the browser's log. Probably because browser is already closed. Need to investigate further.

As a workaround (for now) you can comment out lines 215, 256, 279 in index.js file.

**Comment by Evilweed** [comment]
Fixed issue for Jasmine 2 [v0.4.6](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.4.6)

Issue remains for Jasmine 1 users - didn't figure out fix yet.

**Comment by perwezalamnewscorp** [comment]
Issue #1 - Now all cases are being added into report in fixed version v0.4.6. It working as expected.

Issue #2- It still exist . I have set the preserve directory to false as  preserveDirectory: false,
                 But still facing the same, It does not add all the pending case into the report if the last 
                 case is disabled as xit ( The spec will report as pending and will not be executed.). Run the 
                 below code to see the report. it add only pass or failed case not the pending one.


Example code to reproduce the issue
=================================

describe('INCA Home Page Text verification', function() {
      it('Hello World1',function(){
      	 expect(true).toBe(true);

      });

       xit('Hello World',function(){

      	 expect(false).toBe(true);

      });

});

**Comment by perwezalamnewscorp** [comment]
After setting the preserveDirectory: false , It generate the new report in each run, But issue is not related to not creating new directory every time. The issue is if the last case is temporarily disabled as (xit or xdescribe) then only it does not add all the pending cases into the report. In all other cases it works nicely. It add the report for Pass and Fail test case correctly even the count of all spec matches.

But the problem occurs only when last cases is disabled. Please try running the example code which I shared above then you can see the actual issue

**Comment by Evilweed** [comment]
Next release will include fix for that.

**Comment by Evilweed** [comment]
@perwezalamnewscorp Fixed in [v0.4.7](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.4.7)
