### ISSUE TITLE
performance / amount of write operations to disk

### ISSUE THREAD

**Issue by FDIM** [Evilweed/protractor-beautiful-reporter#45]
Quite a few times I see failures when reporter attempts to write combined data to disk with `shardTestFiles: true` option. After quick lookup it appears that all files (including fonts) are written to report dir after each spec.

Isn't this a bit excessive ? Wouldn't it be possible to 'bundle' everything up when the test is done using data in jsons folder?

**Comment by Evilweed** [comment]
Yep - the best option would be to write JSON files whenever test is done and bundle HTML after all tests are finished. Or we should implement some flag that would switch from bundling after each test to bundling after all tests. And we would need to introduce some console command that would bundle HTML from folder (if for some reason script will break, and no HTML will be generated).
