### ISSUE TITLE
IE issue with progressbar

### ISSUE THREAD

**Issue by DortmunderJunge** [Evilweed/protractor-beautiful-reporter#48]
Internet Explorer does not render the progress-bar on top of the page correctly.
As you can see in the screenshot below, 500+ Tests were executed successfully, but the progress-bar is 100% red. Overall, the progress-bar is not as beautiful as in other browsers.

I figured out, that IE does not support the following code:
```html
<div style="width: {{someAngularExpression()}}"></div>
```
instead one must use 
```html
<div ng-style="{'width': someAngularExpression()}"></div>
<!-- OR -->
<div ng-attr-style="width: {{someAngularExpression()}}"></div>
```
as described in [github angularjs issue](https://github.com/angular/angular.js/issues/2186) and demonstrated in [this plunker](http://plnkr.co/edit/l52wHl?p=preview)

I'm planning to submit a PR later this day 

![protractor-beautiful-reporter ie11-error](https://user-images.githubusercontent.com/4146517/36415336-d0f92a7c-1625-11e8-8912-dc1b1b9bbf61.PNG)

**Comment by Evilweed** [comment]
@DortmunderJunge thanks for reporting and for the upcoming PR! I don't have any Windows machine to test reporter with IE, so kudos :)
