### ISSUE TITLE
Fetching browser logs throws exception in Firefox

### ISSUE THREAD

**Issue by AerionDyseti** [Evilweed/protractor-beautiful-reporter#5]
Because `browser.manage().logs().get('browser').then(function(browserLog) { ... }));`
is not part of the webdriver spec, attempting to fetch browser logs from Firefox will cause webdriver to throw this error:

`WebDriverError: POST /session/36718c58-6808-4ba0-9600-3d33fffc0d30/log did not match a known command`

You may want to consider disabling this feature if the browser is non-Chrome?

**Comment by AerionDyseti** [comment]
See this issue for more details: https://github.com/SeleniumHQ/selenium/issues/2972

**Comment by Evilweed** [comment]
Next release will include fix for that.

**Comment by Evilweed** [comment]
@AerionDyseti Added optional flag to set if You would like to gather logs and added check if browser's name is "chrome" to avoid errors.

Version that includes fix: [v0.4.7](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.4.7)

Can You let me know if it works for You?
