### ISSUE TITLE
Looking for (alternative/custom) charts in Test Report

### ISSUE THREAD

**Issue by codestellar** [Evilweed/protractor-beautiful-reporter#50]
Firstly, Thank you for the awesome work done! 
I am looking for:

- Charts (say pie chart or doughnut) to show test results

**Comment by Evilweed** [comment]
@codestellar there is a "chart" that displays stats in report already. Why is it not enough?

![Chart](https://i.imgur.com/m0zOPeH.png)

**Comment by codestellar** [comment]
@Evilweed yeah I know, but different chart option would be great! Thanks for the prompt reply.

**Comment by miller45** [comment]
No plans to do that
