### ISSUE TITLE
Error message not displaying for failed tests

### ISSUE THREAD

**Issue by firecentaur** [Evilweed/protractor-beautiful-reporter#53]
Hi there, in our Jasmine2 test we have the following code:

expect(viewVideoPg.unpublishVideoBtn.isPresent(), 'Video publish/unpublish button is not found').toBe(false);

However, when this expectation fails, the output in your plugin reads:
Expected true to be false, instead of "Video publish/unpublish button is not found"

Why is this?

How can I fix?

**Comment by Evilweed** [comment]
@firecentaur I've tried similar setup and got the additional message in results:
![Expect message](https://i.imgur.com/GxFHEfS.png)

![Generated html](https://i.imgur.com/7sgc1el.png)

Maybe You have old Jasmine 2 version? Can You update my plugin and jasmine to latest versions and check again?

**You can use helper function to make jasmine print messages differently:**
```
beforeEach(function() {
  var matchers = {
    toEqualBecause: function( value, message ) {
      this.message = function() {
        return "Expected '" + this.actual + "' to equal '" + value + "' because " + message;  
      };

      return this.actual == value;  
    }
  };

  this.addMatchers(matchers);
});
```
**And then my individual expect statements become:**
```
expect( myElement.isDisplayed() ).toEqualBecause( true, myMessage );
```
**This gives an output of:**
```
Expected 'false' to equal 'true' because input_status
```

**Comment by Evilweed** [comment]
Closing as per comment
