### ISSUE TITLE
Changing HTML Report Template

### ISSUE THREAD

**Issue by Purus** [Evilweed/protractor-beautiful-reporter#54]
How can I use a custom HTML template? For example, I want to remove the GitHub link/icon shown at the end of the report.

**Comment by Evilweed** [comment]
@Purus Why do You need to remove this icon? It is my only way to spread the word, get stars and maybe by doing so, get more people using this plugin.

**Comment by Evilweed** [comment]
@Purus if you have some better/superior design for the report then You can attach it here and i will consider adding it.

**Comment by Purus** [comment]
@Evilweed Removing the icon is just an example. I appreciate your time and effort you have spent on this plugin and you deserve it. In general, it would be help to allow customization as in corporate environment, additional links or details can be added to the report.

**Comment by miller45** [comment]
@Purus You can to that already. The report file is just an HTML file you can customize after the e2e test have finished. I explain it in our wiki how you can do that automatically after each e2e test session.
[Customize html report](https://github.com/Evilweed/protractor-beautiful-reporter/wiki/Customize-html-report)
