### ISSUE TITLE
Reporter cause stop test execution when using XIT

### ISSUE THREAD

**Issue by amedvedjev** [Evilweed/protractor-beautiful-reporter#55]
Example of code to reproduce
```
				xit("message", async () => {
					expect(true)
						.toBe(true);
				});

```

When i enable beautiful-reporter it just hangs with "*" in console.  After removing beautiful-reporter execution restoring correctly.

PS Nice reporter!

**Comment by miller45** [comment]
@amedvedjev I cannot reproduce it. Are you in an angular 2-6 context?
