### ISSUE TITLE
For loop breaks reporter to duplicate view.

### ISSUE THREAD

**Issue by amedvedjev** [Evilweed/protractor-beautiful-reporter#59]
code:
```
describe("header", () => {
   for (let i = 1; i < 4; i++) {
      describe("step", () =>...
   }
}
```

Report result:

> header
>    step
> header
>    step
> header
>    step

Expected result:

> header
>    step
>    step
>    step

**Comment by amedvedjev** [comment]
sort by instanceId helped!. maybe make it by default?

**Comment by Evilweed** [comment]
I'll do it in spare time. Thanks for suggestion.

**Comment by Evilweed** [comment]
Closing for now.
