### ISSUE TITLE
Report not generating intermittently

### ISSUE THREAD

**Issue by perwez123** [Evilweed/protractor-beautiful-reporter#6]
I am seeing some times report does not generate even though all test case are passed.
It generated the `combined.json` file which has all the specs detail but `index.html` is empty. It did not throw any error while test were running, but still report not generated.

Please let me know how to get the log while running the test so that i can provide all error details for debugging.

I think this issue must be fixed as soon as possible, because report itself does not get generated

`Environment details`
=====================

Jasmine: `2.X - default version from protractor`
Browser: `Chrome` 
protractor-beautiful-reporter: `0.4.6`

**Comment by perwez123** [comment]
@Evilweed , I really love this report. Comparatively this report is far better than other report available for protractor.

But the small issue is, It does not generate the report intermittently. Now I am facing this very often.
In order to continue using this report, This issue must be fixed as if the report itself not generated then, how will see the result ?

Can you please provide some work around asap to avoid this issue ?

Your help is appreciated.

**Comment by Evilweed** [comment]
Can You create the smallest Spec + Test + Your configuration that reproduces this issue? It does not occur in my setup.

**Comment by Evilweed** [comment]
@perwez123 I've added more logs and changed reporting a bit in new version [v0.4.7](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.4.7)

Can You check if it solves Your problem? If not, can You provide Your config, and some small test case that reproduces this issue?

**Comment by Evilweed** [comment]
I am closing this issue as no information is provided, recent version could fix that, and it does not occur to others.

Feel free to reopen this issue if it still occurs :)

**Comment by epaillous** [comment]
I still have this issue on version 0.4.8

**Comment by martinotu** [comment]
Hi All, 
I am using version 0.5.0  and I see the same issue.
Sometime the report is not generated and its very annoying. Is there any info I can provide to help to fix this?

Cheers
