### ISSUE TITLE
Report multiple failed expects in one it()?

### ISSUE THREAD

**Issue by mbeller-weltenbauer** [Evilweed/protractor-beautiful-reporter#64]
I'm running tests with multiple expects in one it(). When they fail, only the first failed expect ist reported, the rest is ignored.

Is there a way to get all failed expects?

**Comment by miller45** [comment]
Sorry currently only the first is selected (looking at the source code)

**Comment by miller45** [comment]
Fix is commit wait for the next version and you will have it...
