### ISSUE TITLE
Filtering, result counts, & button image issues with v1.2.2

### ISSUE THREAD

**Issue by cstraynor** [Evilweed/protractor-beautiful-reporter#66]
@keymandll @Evilweed 

#65 Pull Request seems to have introduced a few issues.

1. The Pass/Fail/Pending counts no longer show in the colored progress bar at the top of the report.
![capture](https://user-images.githubusercontent.com/7839550/42182384-088d0ec4-7e0c-11e8-84c0-2d2cce181edf.PNG)

2. The Time, Browser, Session ID, and OS filter buttons no longer hide/unhide the details from the test result rows. The details are always showing.
![capture](https://user-images.githubusercontent.com/7839550/42182407-1e1b48be-7e0c-11e8-89d8-bdc219e4e77b.PNG)

3. The triangle icon within the display stracktrace button no longer appears. 
![capture](https://user-images.githubusercontent.com/7839550/42182261-9fefb1b4-7e0b-11e8-8eed-71d2ff61f4e0.PNG)

**Comment by keymandll** [comment]
Submitted a new pull request that fixes the above problems.

**Comment by Mechatrix** [comment]
Is it fixed...we are waiting for it please

**Comment by Evilweed** [comment]
Published new release. Should be fixed.
