### ISSUE TITLE
Can we append our own custom logs(console.log from test) into html report?

### ISSUE THREAD

**Issue by navinchandrac** [Evilweed/protractor-beautiful-reporter#68]
Can we append our own custom logs(console.log from test) into html report?
There is a column for browserLogs. Browser logs and screenshots are not always enough for debugging failed test. Our tests are printing additional logs to console (console.log()). I want to have these logs included in html report (similar columns as browser logs).

Does this report support it? Or do we have any way to achieve this?

**Comment by Evilweed** [comment]
@navinchandrac If You use "console.error()" it should catch it.

**Comment by aleenadavy90** [comment]
Hi! could you elaborate how console.error() will add this to the html report please?

**Comment by ZoeThivet** [comment]
> @navinchandrac If You use "console.error()" it should catch it.

Unfortunately, it's not the case... Too bad, I really would like to add my custom logs.
