### ISSUE TITLE
Progress Bar Count and Buttons Issue

### ISSUE THREAD

**Issue by bharukaRupesh** [Evilweed/protractor-beautiful-reporter#69]
Hi,
I have integrated this reporting feature in my project but I can't see the count of Passed and Failed Test Cases in my progress bar. Also Few of the buttons like Time, Session, Browser are not working.

I have observed that the above-mentioned list of things are working on Windows 2K12 but not on 2k10.

Don't know why is this OS difference?

**Comment by Evilweed** [comment]
@bharukaRupesh i've released new version. Can You check again?

**Comment by bharukaRupesh** [comment]
@Evilweed Thanks for your kind response.
I'll surely check it and will update you.

**Comment by bharukaRupesh** [comment]
@Evilweed I have updated the version and now it's working perfectly fine.
Thanks
