### ISSUE TITLE
App.js timestamp & duration showing Null

### ISSUE THREAD

**Issue by harta11** [Evilweed/protractor-beautiful-reporter#73]
Hello,
I followed the instruction for setting up the protractor-beautiful-reporter.
When i finished running the tests and produced a reporter, the reporter **timestamp** and **duration** is showing as Null.

Below is the screenshot from the app.js file.

![image](https://user-images.githubusercontent.com/15642235/43165221-652413e2-8f61-11e8-9989-796b870a39e1.png)

**Comment by miller45** [comment]
@harta11  I tried to reproduce the phenomenon with my currenty angular 2 and angular 2 environment.
But i never get null for timestamp and duration. Can you post your package.json and your protractor.conf?

**Comment by denizengin** [comment]
I've the same issue when I run protractor through a custom script in package.json, but if I use the command prompt to run protractor, then the duration is populated in the resulting json file. 

I've added some logging into the reporter source, and it seems the started property of the result object is not getting populated, when I run protractor using npm run [customscriptname]

All that the custom script in package.json does is 'protractor [path to protractor config]'.

**Summary**
npm run test-e2e will generate reports, but without duration
`"test-e2e": "webdriver-manager update && protractor ClientApp/test/e2e/protractor.conf.js"`

**Running protractor from the command line** 
generates report with the duration

**Comment by miller45** [comment]
@denizengin I also start protractor via npm but i do not use the "global" command because i work in different teams and configurations. By npm script looks like this...
`node node_modules/protractor/bin/protractor e2e/protractor.conf`
can you try that if makes a differnce?

**Comment by denizengin** [comment]
@miller45 Thanks for the reply.

Pointing to node_modules/protractor in package.json, doesn't make a difference.

Here are the versions:

`    "protractor": "~5.1.2",
    "protractor-angular-screenshot-reporter": "^0.1.2",
    "protractor-beautiful-reporter": "^1.2.4",
    "jasmine-core": "~2.6.2",
    "jasmine-reporters": "^2.0.0",
    "jasmine-spec-reporter": "~4.1.0",
`
npm ->5.6.0
node -> 9.7.0
os -> windows 10

**Comment by miller45** [comment]
@denizengin most version kindof match mine.... the only exception is that i use node 8.11.1 LTS. 
I do not really know if node or other factors are influencing this... but there is one thing you could try.

Go to the source code (index.js) of protractor-beautiful-reporter and search for `function nowString() {` . There you should see `return new Date().toISOString()`.
Replace this with `new Date().getTime();` 

Then see if this makes a difference....and report...

**Comment by miller45** [comment]
Cannot reproduce and no more feedback
