### ISSUE TITLE
Show multiple expect failures

### ISSUE THREAD

**Issue by Brian-Dawson-Nerdery** [Evilweed/protractor-beautiful-reporter#78]
Jasmine provides multiple expect failures to the report, however, the report is currently only showing the first failure. This isn't really helpful since we want to see all of our expect failures, right? That's why we put them there.

I was able to find where the issue is, in [index.js](https://github.com/Evilweed/protractor-beautiful-reporter/blob/c92af386616e603485f98d868aa7e5191cc2581f/index.js#L4582):

Here it is only grabbing the first in the failedExpectations array.
```javascript
metaData.message = (results.failedExpectations[0] || {}).message || 'Failed';
```

Instead, something like the below can be implemented (you can do the same with `.stack`):
```javascript
if (results.failedExpectations[0].message) {
    metaData.message = results.failedExpectations.map(result => result.message);
} else {
    metaData.message = 'Failed';
}
```

This might not be the cleanest way, I'm still pretty new to JavaScript, but I figured this would at least be a good starting point for whoever would work on this. I can also work on this and create a PR, however, it might take me a bit to learn how it works, make sure it works, get time, etc. So, I figured I put this here incase someone can get to it much faster.

Thanks for your time!

**Comment by miller45** [comment]
@Brian-Dawson-Nerdery Thank you for the work...it is true...this is the point of failure....i am already thinking of possible solution... (because the layout of the report has to support these multiple messages else it will become messy if we just put all message in one big string)

**Comment by Brian-Dawson-Nerdery** [comment]
@miller45 - I can show you what I have so far. I have everything working so far, at least that I'm aware of. The only issue that I'm having right now is a CSS issue with the stack trace `<pre>` tags - for whatever reason they have giant space around the text - currently looking into this.

**Comment by Brian-Dawson-Nerdery** [comment]
Created a PR for this: #79

**Comment by miller45** [comment]
@Brian-Dawson-Nerdery Do you want a release right-away? I will send the repo owner a mail...

**Comment by Brian-Dawson-Nerdery** [comment]
@miller45 - I'd prefer this as soon as possible, but I'm Ok with waiting a bit if he's busy. Thanks :)

**Comment by miller45** [comment]
In the meantime you could use it directly from git (if your team and your company firewall allows it) by using:
`"protractor-beautiful-reporter": "git+https://github.com/Evilweed/protractor-beautiful-reporter.git"`,
in your the `devDependencies `section of your `package.json`

**Comment by miller45** [comment]
@Brian-Dawson-Nerdery did not notice that Evilweed did the npm release on 25 August already...
so closing this now

Fix was released on 25. Aug. 2018 on v1.2.5.
