### ISSUE TITLE
report not generated

### ISSUE THREAD

**Issue by epaillous** [Evilweed/protractor-beautiful-reporter#8]
Hello, 

Sometimes, the report.html is empty and I do not understand why. It seems to be random. 
Here is my protractor.conf.js : 

```
var SpecReporter = require('jasmine-spec-reporter').SpecReporter;
var HtmlReporter = require('protractor-beautiful-reporter');

exports.config = {
  allScriptsTimeout: 11000,
  specs: [
  './e2e/**/*.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  baseUrl: 'http://localhost:8080/',
  framework: 'jasmine2',
  jasmineNodeOpts: {
    showColors: true
  },
  suites: {
    login: 'e2e/login/**/*.e2e-spec.ts',
    servicesList: 'e2e/services/services-list/**/*.e2e-spec.ts',
    serviceOverview: 'e2e/services/service-overview/**/*.e2e-spec.ts',
    serviceDetail: 'e2e/services/service-detail/**/*.e2e-spec.ts',
    planning: 'e2e/services/**/*.e2e-spec.ts',
    signup: 'e2e/signup/**/*.e2e-spec.ts',
    newPermuteRequest: 'e2e/requests/new-request/new-permute-request/**/*.e2e-spec.ts',
  },
  useAllAngular2AppRoots: true,
  beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e'
    });
  },
  onPrepare: function() {
    jasmine.getEnv().addReporter(new SpecReporter());
    var protractorImageComparison = require('protractor-image-comparison');
    browser.driver.manage().window().setSize(375, 668);
    browser.driver.manage().window().setPosition(0, 0);
    browser.protractorImageComparison = new protractorImageComparison(
    {
      baselineFolder: 'e2e/screenshots_baseline',
      screenshotPath: 'e2e/screenshots_from_tests',
      autoSaveBaseline: true
    }
    );
    jasmine.getEnv().addReporter(new HtmlReporter({
      baseDirectory: 'reports/testsE2E',
      preserveDirectory: false
    }).getJasmine2Reporter());
  }
};
```

Thanks ! (I really like this package! ;) )

**Comment by Evilweed** [comment]
Please attach JSON files before combining and combined JSON file when this issue occurs.
Can You also try to narrow down to a specific test case that makes HTML file not being generated?

**Comment by jakjothi** [comment]
@Evilweed me too facing same problem, i am having more than 300 tests
Both app.js and report.html zero bytes

`
const { SpecReporter } = require('jasmine-spec-reporter');
const HtmlReporter = require('protractor-beautiful-reporter');

exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    './e2e/CRM/**/*.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  // seleniumAddress: 'http://localhost:4444/wd/hub',
  baseUrl: 'http://localhost:4200/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
  },
  onPrepare() {
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));

    jasmine.getEnv().addReporter(new HtmlReporter({
      baseDirectory: 'tmp/screenshots'
    }).getJasmine2Reporter());
    // implicit and page load timeouts
    browser.manage().timeouts().pageLoadTimeout(40000);
  }
};
`

<img width="742" alt="screen shot 2017-07-13 at 5 33 08 pm" src="https://user-images.githubusercontent.com/2713170/28165437-658df566-67f1-11e7-92f4-41bb975b0bd7.png">

**Comment by Evilweed** [comment]
@jakjothi @epaillous Could You zip all the separate JSON files and attach them here? This way i could try to debug why this is happening.

**Comment by Evilweed** [comment]
Please try if this fixes Your issue. And if not then please tell me if You have any errors in log.
[https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.0](https://github.com/Evilweed/protractor-beautiful-reporter/releases/tag/v0.5.0)

**Comment by leonardotdleal** [comment]
Hello @Evilweed 

I'm using the protractor-beautiful-reporter in my project, but most of the time the report is not generated. 
Even upgrading to the versions reported, app.js files and leave White report.html. 

Can you help?

**Comment by Edgar56** [comment]
Same problen app.js and report.html empty, maybe someone know how to fix issue ?

**Comment by ninogomez** [comment]
I'm currently having this issue right now. app.js and html file is not generated. I have older json files and can't view the report now.

**Comment by Rajeshwoyce** [comment]
Still i'm facing this issue app.js and html file is not generated. could you please help ?
