### ISSUE TITLE
unable to merge report.html into single file

### ISSUE THREAD

**Issue by SwathiJayabharathi** [Evilweed/protractor-beautiful-reporter#83]
i want my html report to be in single html file. But it is creating separate folder for each and every minute. So report.html is generated for first folder alone. For remaining folders, screenshot alone saved but html report is not generated.

onPrepare: () => {
        let globals = require("protractor");
        let browser = globals.browser;
        browser.manage().window().maximize();
        browser.manage().timeouts().implicitlyWait(5000);

        let HtmlReporter = require('protractor-beautiful-reporter');
        let path = require('path');
        let excuteUser = process.env.USERPROFILE.split(path.sep)[2];

        jasmine.getEnv().addReporter(new HtmlReporter({
            preserveDirectory: false,
            docTitle: "Report Generated By: " + excuteUser,
            takeScreenShotsOnlyForFailedSpecs: false,
            screenshotsSubfolder: 'images',
            jsonsSubfolder: 'jsons',
            baseDirectory: 'test-report',
            docName: 'index.html',

            pathBuilder: function pathBuilder(spec, descriptions, results, capabilities) {

                let currentDate = new Date(),
                    day = currentDate.getDate(),
                    month = currentDate.getMonth() + 1,
                    year = currentDate.getFullYear(),
                    hours = currentDate.getHours(),
                    minute = currentDate.getMinutes();

                let validDescriptions = descriptions.map(function (description) {
                    return description.replace('/', '@');
                });

                return path.join(
                    day + "-" + month + "-" + year + "-" + hours + "-" + minute,
                    // capabilities.get('browserName'),
                    validDescriptions.join('-'));
            }
        }).getJasmine2Reporter());

    }

Please help me how to resolve it and how to generate single html report for all specs in one suite.

**Comment by miller45** [comment]
@SwathiJayabharathi it is making a different for every minute because the pathBuilder is called every time a test has been finished...
Move the "`let currentDate`" line nelow you "letexecueUser

**Comment by SwathiJayabharathi** [comment]
@miller45 Thank you :)
