### ISSUE TITLE
Progress bar: Failed tests number not visible with many tests

### ISSUE THREAD

**Issue by amedvedjev** [Evilweed/protractor-beautiful-reporter#84]
Steps to reproduce:
1) Run suite with about 1000 tests where e.g. 15 will fail.
2) observer report

Result: Fails number counter not visible due to small length.
Suggestion: leave MIN size of Fail tests so at least 3 numbers can be visible.

**Comment by miller45** [comment]
@amedvedjev i will have look at it this evening ...i think a simple solution would be possible.

**Comment by miller45** [comment]
@amedvedjev now fixed in master (we show tooltips with the errors when the bars are tool small)
You have to wait for the next release...(i cannot do that)

**Comment by miller45** [comment]
Fix was released on 25. Aug. 2018 on v1.2.5.
