### ISSUE TITLE
Feature Request: Take Screenshot for expectations

### ISSUE THREAD

**Issue by KaiReichart** [Evilweed/protractor-beautiful-reporter#88]
For my Tests I need Screenshots of expectations, would that be at all possible?
Like the Plugin  [protractor-screenshoter-plugin](https://github.com/azachar/protractor-screenshoter-plugin) has it.

**Comment by miller45** [comment]
@KaiReichart  In theory in might be possible...but currently we do not support it...

**Comment by miller45** [comment]
Closing ...merged the request in #102
