### ISSUE TITLE
How to Table Values and verify it is displayed under particular column

### ISSUE THREAD

**Issue by SwathiJayabharathi** [Evilweed/protractor-beautiful-reporter#89]
I am able to get the values from the table but i am unable to verify that values are displayed in appropriate columns. 

Name | Place | SubmittedDate&Time
-- | -- | --
Arun | Chennai | 08/16/2018   12:55:23 PM
John | London | 08/18/2018   07:12:03 AM

How to verify the table generated at runtime.

**Comment by miller45** [comment]
@SwathiJayabharathi i think this question should be placed in in a protractor support forum
