### ISSUE TITLE
Buttons "Time", "Browser", "Session ID", and "OS" on the top right bar does not work.

### ISSUE THREAD

**Issue by Jveyrat** [Evilweed/protractor-beautiful-reporter#93]
Hi there,

It looks like the buttons "Time", "Browser", "Session ID", and "OS" on the top right bar does not work.
They should display/hide the related content in the report but actually, all the information are displayed, 

To reproduce:
Have a report.
Click on "Browser" on the top right bar for example.

Expected:
"Browser" columns should be hidden/displayed on the report.

Currently:
Column is always shown.

I use the default configuration for the plugin.

**Comment by miller45** [comment]
@Jveyrat they work for me locally and also in my company. When you press F12 do you see any exceptions in the console? What browers do you use?
Can your post your package.json and your node version, so that i can reproduce the environment?

**Comment by Jveyrat** [comment]
Hi @miller45 I don't have any exceptions on my page.
I use Chrome 68.0.3440.106 and Node 8.11.3

I've use the reporter since several weeks now, and I saw it working.
I can't tell exactly since when it starts having trouble.

Here is my protractor.conf file.

exports.config = {

    params: {
        baseURL: '',
        country: ''
    },

    // The address of a running selenium server. To be commented if you want to run your test using Sauce Labs as remote Selenium Server
    seleniumAddress: 'http://localhost:4444/wd/hub',

    // Capabilities to be passed to the webdriver instance.
    capabilities: {
        browserName: 'chrome',
        chromeOptions: {
            mobileEmulation: {
                deviceName: 'iPhone X'
            }
        }
    },

    // Spec patterns are relative to the location of the spec file. They may
    // include glob patterns.
    suites: {
        feature: ['tests/e2e/feature/*Spec.js']
    },

    // Options to be passed to Jasmine-node.
    jasmineNodeOpts: {
        showColors: true, // Use colors in the command line report.
    },

    onPrepare: function () {

        // Configure the HTML reporting tool:
        // https://github.com/tiberiuzuld/protractor-beautiful-reporter/blob/master/README.md
        var HtmlReporter = require('protractor-beautiful-reporter');
        jasmine.getEnv().addReporter(new HtmlReporter(
            {
                baseDirectory: 'tmp/screenshots'
                , screenshotsSubfolder: 'images'
                , jsonsSubfolder: 'jsons'
                , docTitle: 'CCP Non regression test report'
                , preserveDirectory: false
            }).getJasmine2Reporter());
    }
};


And my package.json file:

`{
  "name": "test-nonregression",
  "description": "Non regression test",
  "dependencies": {
    "protractor": "^5.3.2",
    "protractor-accessibility-plugin": "^0.3.0",
    "protractor-image-comparison": "^2.0.0"
  },
  "bin": {
    "protractor": "bin/protractor",
    "webdriver-manager": "bin/webdriver-manager"
  },
  "devDependencies": {
    "protractor-beautiful-reporter": "^1.2.2",
    "protractor-jasmine2-html-reporter": "0.0.7",
    "protractor-video-reporter": "^0.3.0",
    "protractor-zephyr-reporter": "^1.2.1"
  }
}`

**Comment by miller45** [comment]
@Jveyrat please install the latest version of protractor-beautiful-reporter (it is 1.2.4). At best delete your node_modules folder. Enter `"protractor-beautiful-reporter": "^1.2.2"` in your `package.json` and then do a fresh `npm install`.
I can reproduce the button problem with version 1.2.2 but it has been fixed in Version 1.2.3 as you can see in the release log `https://github.com/Evilweed/protractor-beautiful-reporter/releases`

**Comment by Jveyrat** [comment]
@miller45 Works fine now. Thanks for the tips. I'll read release note details next time before posting :)
