### ISSUE TITLE
Stack strace on terminal

### ISSUE THREAD

**Issue by shulolo** [Evilweed/protractor-beautiful-reporter#98]
Hi everyone,

I decided to use protractor-beautiful-reporter in my project in order to have screenshot and report.
Before that, I used jasmine-spec-reporter, and I had report on stack trace on the terminal.
I like this feature of jasmine-spec-reporter, but I did not find this on protractor-beautiful-reporter.

So I would like to know if it's possible to have the screenshot and the reporter on one hand, and also have the stack trace in the terminal on the other hand?

I tried to create two reporter object on my config (HtmlReporter and SpecReporter), but jasmine can add only one.

Thank you in advance.

**Comment by miller45** [comment]
@shulolo I added the answer to our wiki. Closing the issue.
